### ISSUE TITLE
ul and ol description is backwards

### ISSUE THREAD

**Issue by smullarkey** [milligram/milligram#10]
Just wanted to point out that the < ol > and < ul > tags are backwards in the list description (http://milligram.github.io/#lists)

"The unordered list use < ol > element will be marked with a outline circles, the ordered list use < ul > element"

**Comment by Mortiferr** [comment]
Appears to be fixed.

**Comment by cjpatoilo** [comment]
Hello @smullarkey 
Thanks for attention!
