### ISSUE TITLE
Headings look different?

### ISSUE THREAD

**Issue by Orbyt** [milligram/milligram#102]
Heading on the milligram example page: http://prntscr.com/bt1vmy

My headings on a blank page with milligram added: http://prntscr.com/bt1vs0

As you can see, they look very different. Why is this? The css when inspecting seems to be the same. I've also tried on another browser. What might be the issue?

**Comment by Mortiferr** [comment]
It looks like they just added `font-weight` or something similar to make it thinner.

Upon further investigation I found it.
```
h1, h2, h3, h4, h5, h6 {
    font-weight: 300;
    margin-bottom: 2rem;
    margin-top: 0;
}
```

As you can see, `font-weight: 300;` is making the letters look thinner and less bold. Milligram is a framework, not a full website maker so it's meant to be customized.

**Comment by Orbyt** [comment]
@Mortiferr No, thats not it. As mentioned, the css is exactly the same. I was having this problem with with another css framework as well. I think the issue was I was assuming that the font the framework used was included, and did not need to be explicitly included.

This seemed to fix the issue on the other framework, so I would assume it is also the fix for this issue. I have not tested it, but I'll go ahead and close this for now.
