### ISSUE TITLE
cssnext version

### ISSUE THREAD

**Issue by steven-klein** [milligram/milligram#106]
I've created a branch that uses [cssnext](http://cssnext.io/) syntax.  I noticed there was at one time a postcss version of Milligram, and I can see a good argument for avoiding Postcss specifically, since the Sass or Less versions could be processed by someones Postcss build process, but I like the idea of having a version written with cssnext syntax, since it's potentially future css.

In the build I only used one additional Postcss plugin, postcss-imports, just so the builds would be concatenated.  

[Here it is](https://github.com/steven-klein/milligram-cssnext/tree/cssnext) if you want to bring it into the mix.  I'd be happy to maintain it.

**Comment by cjpatoilo** [comment]
Hi @steven-klein 
Sounds good. I appreciate your interest. I create the repository with what name?

`milligram-cssnext`
`milligram-postcss`
`milligram-???`

**Comment by steven-klein** [comment]
I went with ``milligram-cssnext`` since the other repositories were named for the syntax that is being used.

**Comment by cjpatoilo** [comment]
Hi @steven-klein check it https://github.com/milligram/milligram-cssnext 
Let me know if there is anything else I can help. It will be a pleasure to participate in this project

**Comment by cjpatoilo** [comment]
@steven-klein Nice job!! 
https://github.com/milligram/milligram-cssnext/pull/1
