### ISSUE TITLE
Flex box issues with Safari.

### ISSUE THREAD

**Issue by enkota** [milligram/milligram#110]
Hey,

I noticed today while browsing the demo site on chrome that the flex grid was going full width on smaller screens - something I suggest a while back [here](https://github.com/milligram/milligram/issues/83).

<img width="1046" alt="milligram safari issue" src="https://cloud.githubusercontent.com/assets/13979799/17456652/229f281e-5bd7-11e6-95d8-c3c67a52a213.png">

(Chrome on left, Safari on right)

On Safari (my main browser) I noticed that they are still appearing in their normal state. Is this meant to happen? I shall have a look into the code to see if I can amend.

Thanks!

Scott

**Comment by enkota** [comment]
As a follow-up to this post, I discovered that disabling - 

`/* flex-direction: row; */ `on the `.row `class will fix the issue at smaller resolutions on Safari.

**Comment by cjpatoilo** [comment]
@enkota Could you tell me the version of Safari and the name and version of the platform?

**Comment by v3rmin** [comment]
Did you ever release a new version?

**Comment by enkota** [comment]
@v3rmin I don't think so but you can easily change the breakpoints.

So for instance change 

```
@media (min-width: 40rem) {
  .row {
    flex-direction: row;
    margin-left: -1.0rem;
    width: calc(100% + 2.0rem);
  }
  .row .column {
    margin-bottom: inherit;
    padding: 0 1.0rem;
  }
}
```

to

```
@media (min-width: 60rem) {
  .row {
    flex-direction: row;
    margin-left: -1.0rem;
    width: calc(100% + 2.0rem);
  }
  .row .column {
    margin-bottom: inherit;
    padding: 0 1.0rem;
  }
}
```
