### ISSUE TITLE
Change .column to .element

### ISSUE THREAD

**Issue by akmur** [milligram/milligram#114]
Just my two cents on the naming side of things. 

I think it would be better to use .row-element or .element rather than .column, because we might have situations where columns get stacked or shifted around thanks to flexbox super powers, and they are not columns anymore at that point, so the naming seems odd.

What do you think?

Thanks for the nice library

**Comment by cjpatoilo** [comment]
@akmur You're right and it seems to make sense. For now I prefer to keep this term by doing more semantic. Anyway thank you for the contribution.
