### ISSUE TITLE
Flex Modifiers don't seem to be working

### ISSUE THREAD

**Issue by jkinley-sds** [milligram/milligram#116]
How do I use .row-wrap, .col-bottom, etc? I have tried numerous ways  and they do not seem to work. Also, I don't see the breakpoints working either. I apologize if this is my ignorance, but I was unable to see these things identified in the docs. I hope this helps...

### Version info

**Milligram:**
https://cdnjs.cloudflare.com/ajax/libs/milligram/1.1.0/milligram.css

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**
NA

### Test case

http://codepen.io/jkinley/pen/PGYXvJ

### Steps to reproduce

I have tried numerous ways to get  modifiers like .row-wrap .col-top, etc to work and I am lost. I have looked at the Scss and tried several classes and they do not seem to work.

I have reviewed the docs and there are no examples of how to use these advanced modifiers.

### Expected behavior

.row-wrap should invoke flexbox to wrap.
.col-bottom should make flex items align to the bottom.

### Actual behavior

the classes don't have an effect.

**Comment by cjpatoilo** [comment]
Hi @jkinley-sds 
Sorry if this has caused any problems, then less will be available the next version of Milligram with this issue fixed. #88
