### ISSUE TITLE
Matching container padding and row gutter (grid)

### ISSUE THREAD

**Issue by bkgunby** [milligram/milligram#117]
https://github.com/milligram/milligram/blob/master/src/_Grid.sass#L9

Is there a reason why the container's padding doesn't match the row's gutter? Currently the container's padding is `2.0rem` and `1.0rem` for the gutter. Just wondering.

**Comment by cjpatoilo** [comment]
Hi @bkgunby 
Yes. The columns have a lateral spacing, so the first and last columns of each row will need this padding.

Let us know if you need anything else.

**Comment by cjpatoilo** [comment]
Hey @bkgunby For now I will close this Issue. Feel free to reopen this issue if this doesn't do the trick for you.
