### ISSUE TITLE
Hiding/showing elements based on screen size

### ISSUE THREAD

**Issue by joekaiser** [milligram/milligram#118]
Is it possible to hide or show an element based on the current screen size? For example, hiding certain images on mobile, or showing extended navigation options when the screen size permits.

**Comment by cjpatoilo** [comment]
Hi @joekaiser 

Yes, you can use the features of CSS3 - Media Queries https://css-tricks.com/logic-in-media-queries/

**Comment by joekaiser** [comment]
Yes, I am familiar with that and it is what i am currently using. I made a visible-desktop class I can apply to content. I guess I was wondering if a similar class was built in, and I was overlooking it. Thanks for the quick reply

(Milligram is quickly becoming my favorite CSS framework. I love how small and light it is. Keep up the good work! )

Sent from Nine
________________________________
