### ISSUE TITLE
Hi! Milligram include support  for responsive web design?

### ISSUE THREAD

**Issue by Anfelroth** [milligram/milligram#125]

**Comment by cjpatoilo** [comment]
Hi @Anfelroth 
Yes. On the website talks about one of the techniques (Mobile First) you can use. See more examples here: https://milligram.github.io/#tips

**Comment by Anfelroth** [comment]
Wow! Thanks a lot, useful info. Cheers!

**Comment by cjpatoilo** [comment]
@Anfelroth You're welcome! Let me know if you need anything else.
