### ISSUE TITLE
Feature: Add `src` folder to an npm distribution 

### ISSUE THREAD

**Issue by eugene-p** [milligram/milligram#126]
Thanks a lot for a fantastic framework.

I think it would be great to have `src` folder a part of npm(bower)

`npm install milligram` - would also pull src folder

That would remove need of maintaining separate `miligram-scss` repository and package.

All goodies in one place.

**Comment by cjpatoilo** [comment]
Hi @eugene-p 
This thread (#55) might clarify your question. Let us know if you need anything else. 

Thank you for asking though, for now I'm closing this issue.
