### ISSUE TITLE
Nested grid system

### ISSUE THREAD

**Issue by reygoch** [milligram/milligram#128]
Is it possible to have nested grid system. Currently if I try to have column within column padding doesn't align with outher parts of the grid.

We should be able to mark column as row as well, which would cause it to loose padding, like this :
```
...
// column that is also a row, thus it has 50% width but 0 padding
<div class="column column-50 row">
        // nested column, aligns perfectly with rest of the grid
        <div class="column column-50">Nested</div>
</div>
...
```

This would allow much higher flexibility when designing semantic markup, because sometimes I want to have container that is a column within some other container, but it acts as a row to it's children.

**Comment by cjpatoilo** [comment]
Hey @reygoch Thank you for sharing your thoughts. Your point of view is great. At first I thought so too, until I came across the [Single Responsibility Principle](https://www.toptal.com/software/single-responsibility-principle). 

For now I will not touch it, but in the future it will be a great idea. Feel free to submit these improvements or reopen this issue.
