### ISSUE TITLE
No <figcaption> styling.

### ISSUE THREAD

**Issue by garretwilson** [milligram/milligram#130]
I sure wish I could find a decent stylesheet for reports that looks decent out of the box and provides some acceptable default for all HTML5 elements. You'd think the web would be crawling with such stylesheets.

Milligram doesn't provide any styling whatsoever with for `<figcaption>`. If I put a caption on a figure (e.g. containing an image) it doesn't look like a caption --- it doesn't look any different than the rest of the text.

I would accept any reasonable defaults.

Maybe Milligram isn't what I'm looking for. If providing a default style for all semantic elements is not the purpose of Milligram, could someone point me to something that is? Thanks.

**Comment by cjpatoilo** [comment]
Hi @garretwilson 

Great idea, Great idea, who knows in the future? Now I have no intention of adding new features. I want to make the framework even lighter and focused only on minimal support. 

You should look for something more specific to your project. Anyway thanks for the idea.
