### ISSUE TITLE
When updating meteor with 1.4.2.3 I get an error that this version is not binary compatible. 

### ISSUE THREAD

**Issue by bmcgonag** [milligram/milligram#135]
### Version info
Trying to install version 1.2.0 with a new Meteor app.

**Milligram:**
Milligram
**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**
Meteor v. 1.4.2.3

### Test case
run the `meteor` command and I get the error message. or
run the `meteor update --all-packages` command and I get the error message.

**Comment by bmcgonag** [comment]
Actual error:

 While checking for milligram:milligram@1.2.0:
   error: No compatible binary build found for this package. Contact the
   package author and ask them to publish it for your platform.

I don't actually have milligram:milligram@1.2.0 in my packages file, but I'm guessing that's the version it's trying to put.

**Comment by cjpatoilo** [comment]
Hey @bmcgonag You can try again, now it's working fine. BTW thank you for reporting this issue. Feel free to reopen this issue if this doesn't do the trick for you.

**Comment by bmcgonag** [comment]
Unfortunately still get this when I add

`milligram:milligram` to my packages on Meteor 1.4.2.3 version.

>    While checking for milligram:milligram@1.2.0:
   error: No compatible binary build found for this package. Contact the
   package author and ask them to publish it for your platform.
   
=> Your application has errors. Waiting for file change.
