### ISSUE TITLE
iPhone 6/7 Plus @ min-width

### ISSUE THREAD

**Issue by dnohr** [milligram/milligram#136]
Hi, thanks for working on this framework.

iPhone 6/7 Plus and Google Mobile Friendly test (1) is showing the full version instead of the responsive grid. Is there any thoughts on increasing the "min-width" for grid and headlines?

**Current**:
`@media (min-width: 40rem) {`

**Quick fix**:
`@media (min-width: 45rem) {`

### Version
- milligram: 1.2.3
- normalize.css: 5.0.0

Thanks.

1. https://search.google.com/search-console/mobile-friendly

**Comment by rafaelkallis** [comment]
Sharing same though as @dnohr  

`@media (min-width: 45rem)` also seemed to have fixed the iPhone 6+ responsiveness for me.

**Comment by cjpatoilo** [comment]
@dnohr @rafaelkallis Thank you for reporting this issue. I'll analyze this problem ASAP

**Comment by benjamin79** [comment]
Any update?

**Comment by cjpatoilo** [comment]
@benjamin79 Apparently, yes. The expected behavior should be this one:

![milligram-mobile](https://user-images.githubusercontent.com/1542831/82407678-2d7d6b00-9a40-11ea-8d9c-ef799ecd44bd.gif)

@dnohr @rafaelkallis Please, if necessary feel free to reopen or open a new!
For now, I will close this issue.

**Comment by iplanwebsites** [comment]
Getting this bug 5 years later on an ios device and fixed it using the same fix. 
`@media (min-width: 45rem) {` 

This isn't possible to replicate in browser emulators, so this makes troubleshooting the issue especially painful. It'd be great to patch the lib or find out why ios (both chrome and safari) don't handle the 40rem value as expected.
