### ISSUE TITLE
 Missing style for input[type=date]

### ISSUE THREAD

**Issue by rafaelgondim** [milligram/milligram#137]
And for datetime

**Comment by Arrow7000** [comment]
Yes please!

**Comment by adiramardiani** [comment]
Yes please @cjpatoilo 

I think milligram must provide all html5 input type https://www.w3schools.com/Html/html_form_input_types.asp

**Comment by cjpatoilo** [comment]
@rafaelgondim @Arrow7000 @adiramardiani This feature was added in the new version.

For now, I will close this issue. Please, feel free to reopen or open a new one.
