### ISSUE TITLE
"Age range" doesn't show on the main page

### ISSUE THREAD

**Issue by rspeer** [milligram/milligram#140]
### Version info

**Milligram:**
This is a bug on the main page, milligram.github.io.

### Test case

https://milligram.github.io/

### Steps to reproduce

* Load https://milligram.github.io/
* Scroll to the "forms" example

### Expected behavior

The "age range" label should appear above its dropdown.

### Actual behavior

The "age range" label is not there, because the HTML of the page is different from the HTML of the example. The HTML for the label is missing.

**Comment by cjpatoilo** [comment]
Oops.. Thank you for the info @rspeer
