### ISSUE TITLE
Remove gap between table borders

### ISSUE THREAD

**Issue by tuunanen** [milligram/milligram#141]
I created a table using default Milligram styles. I noticed there's a small gap between the borders of adjacent table cells, making the table look unfinished.

![milligram-table-border-spacing](https://cloud.githubusercontent.com/assets/1409675/21507917/363fad48-cc85-11e6-93a4-6984f79ce95a.png)

The issue is caused by browser default styles where `border-collapse` is separate, and `border-spacing` is not 0. These defaults seem to apply latest to Firefox, Chrome, and Safari, based on my quick test.

### Version info

**Milligram:**
1.2.4

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**
n/a

### Test case

[Milligram Table docs](https://milligram.github.io/#tables)

(Zooming helps to see the issue)

### Steps to reproduce

Create an HTML table using default table styles provided by Milligram.

### Expected behavior

Horizontal borders separating rows should be single lines.

### Actual behavior

There is a small gap between the borders of adjacent table cells.

**Comment by cjpatoilo** [comment]
@tuunanen Thanks for PR!
