### ISSUE TITLE
Breadcrumb component

### ISSUE THREAD

**Issue by kushvarma** [milligram/milligram#148]
Breadcrumbs are highly used on most of the websites especially in blogs, drupal sites etc. We should create a style for breadcrumbs as well, I am thinking to work on it and provide a simple yet beautiful breadcrumb which goes with this theme. 
if anyone is already worked on this, please let me know or if someone is interested in working on this let me know. 
This is one of the most intriguing themes I came across in recent time.

**Comment by szul** [comment]
I think it's a good value add.

**Comment by cjpatoilo** [comment]
I agree with @szul. Breadcrumbs are awesome! 
@kushvarma thank you for your idea.

In the future, I would like to extend Milligram to be more than 'a fast and clean starting point, with 2kb size'.

For now, I will close this issue.
