### ISSUE TITLE
Use semantic grid

### ISSUE THREAD

**Issue by corsonr** [milligram/milligram#149]
I was wondering if Milligram wouldn't become really really awesome if the grids were semantic like Bourbon neat for example. Instead of having to apply a CSS class the whole grid could be defined within the CSS. What do you think @cjpatoilo ?

**Comment by cjpatoilo** [comment]
@corsonr The idea seems to be great. We need to work to develop a better grid system without forgetting to make it as light as possible.

**Comment by franzejr** [comment]
Are [CSS Grids](https://caniuse.com/#feat=css-grid) something to have in mind when developing the better grid system, @cjpatoilo?

**Comment by cjpatoilo** [comment]
@corsonr @franzejr Can you explain more for your ideas?

I plan to improve the grid system of the Milligram in the next major version.

**Comment by jasny** [comment]
Why not remove the grid component completely? You can easily do columns and grids through CSS grids. No point using flexbox and/or abusing classes like `column-50.column-offset-25`.

**Comment by cjpatoilo** [comment]
> Why not remove the grid component completely? You can easily do columns and grids through CSS grids. No point using flexbox and/or abusing classes like `column-50.column-offset-25`.

> Milligram provides a minimal setup of styles for a fast and clean starting point.

@jasny I agree that there is some reason in your words.
Today, use CSS Grid and Flexbox is very ease but I disagree about removing the grid component.

The grid component in Milligram does not cost many kb and the main motivation to keep this feature is to provide a minimal setup of styles for a fast and clean starting point.

So I can't see a legitimate reason to remove the grid component from Milligram.

**Comment by cjpatoilo** [comment]
> Why not remove the grid component completely? You can easily do columns and grids through CSS grids. No point using flexbox and/or abusing classes like `column-50.column-offset-25`.

@jasny I agree that there is some reason in your words.
Today, use CSS Grid and Flexbox is very ease but I disagree about removing the grid component.

The grid component in Milligram does not cost many kb and the main motivation to keep this feature is to provide a minimal setup of styles for a fast and clean starting point.

So I can't see a legitimate reason to remove the grid component from Milligram.

**Comment by cjpatoilo** [comment]
Guys, for now, I will close this issue. 
Please, feel free to reopen or open a new one.
