### ISSUE TITLE
variable font-family

### ISSUE THREAD

**Issue by whodidthis** [milligram/milligram#150]
Hopefully this issue hasn't come up before, but would it make sense to switch to using a variable for milligram's font-family? That way people who don't design around Roboto could use for example the native font stack as described [here](https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/#approach-b) and make milligram even lighter. Native stack is also a default in [bootstrap](https://github.com/twbs/bootstrap/blob/d79b5563730e8188ca7ee5dfc71503d82eb297b4/scss/_variables.scss#L244).

**Comment by fooksupachai** [comment]
like you say I think that font-family  should be adjusted to the value.

**Comment by cjpatoilo** [comment]
@whodidthis make sense to me. I have plans to implement this feature in the next version.

Thank you for your idea. For now, I will close this issue.
Please, feel free to reopen or open a new one.
