### ISSUE TITLE
Navigation Bar Issues

### ISSUE THREAD

**Issue by warrenkc** [milligram/milligram#153]
Hi. 
I have created a navigation bar that I want to add to an html page.
See: https://codepen.io/anon/pen/NprrMY

However when using with the Milligram CSS the menu hover's stop working for the submenus.
https://codepen.io/anon/pen/ryLMWO

**Comment by marcusasplund** [comment]
milligram has margins for ul and li:s, you have to reset those with 
````css
margin: 0;
````

 to make it work with your menu css
https://codepen.io/anon/pen/ryXVyq
````css
#cssmenu,
#cssmenu ul,
#cssmenu ul li,
#cssmenu ul li a,
#cssmenu #head-mobile {
  border: 0;
  list-style: none;
  line-height: 1;
  display: block;
  position: relative;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  text-transform: uppercase;
  margin: 0;
}

**Comment by nirajrajgor** [comment]
@warrenkc Check the above solution and close the issue if its working.

**Comment by warrenkc** [comment]
Wow. Nice.
