### ISSUE TITLE
Checkboxes and radio button funkiness

### ISSUE THREAD

**Issue by PurpleBabar** [milligram/milligram#154]
Hi,
I find the checkboxes and radio buttons a little bit sad for the moment. I made a jsfiddle so you can see a nicer way to display them :)

[TheFiddle](https://jsfiddle.net/purplebabar/1mx35bxc/7/)

Tell me what you think of it @cjpatoilo :)
cheerz

**Comment by shellscape** [comment]
beautiful @PurpleBabar. should definitely open a PR for this.

**Comment by PurpleBabar** [comment]
Thanks :) i'll probably open one if @cjpatoilo agree :)

**Comment by nateberkopec** [comment]
Those look great!

Aren't there issues with styling form elements in Firefox though? Or am I making that up?

**Comment by PurpleBabar** [comment]
Thanks :)

I d'ont see anything wrong in firefox, could you send a screen of what it looks like for you @nateberkopec ? thks 👍

**Comment by nateberkopec** [comment]
@PurpleBabar Ignore me! Looks great in latest FF. Used to be with FF that they didn't let you style a lot of form stuff, I guess that's changed.

**Comment by cjpatoilo** [comment]
@PurpleBabar It's very impressive. Thank you!
