### ISSUE TITLE
Why margin-left: -1rem?

### ISSUE THREAD

**Issue by merlinpatt** [milligram/milligram#156]
For rows on screens larger than mobile, you specify `margin-left: -1.0rem;`. [Here is a link to the specific line.](https://github.com/milligram/milligram/blob/master/src/_Grid.sass#L153)

Why is this the case?

**Comment by nateberkopec** [comment]
This is because columns have `padding: 0 1rem`. Rows always contain columns, so to keep the gutter size consistent you have to move the row to the left to compensate.

**Comment by edwardbattistini** [comment]
I am not sure to understand too... as I if I keep that -1rem then there is a gap on the right of the page.
I have removed it in the css and it works perfectly...

**Comment by cjpatoilo** [comment]
@merlinpatt @edwardbattistini

In CSS, margin properties can utilize negative values (padding cannot). The syntax is nearly the same as the default, positive margin utilities, but with the addition of n before the requested size. These utilities are ideal for customizing grid column gutters across breakpoints.

Rows have a negative left/right margin of -1.0rem. The Container padding of 2.0rem is used to counteract the negative margins of the Row. This is to keep content evenly aligned on the edges of the layout. If you don't put a Row in a Container, the Row will overflow it's container, causing an undesirable horizontal scroll.

**Comment by cjpatoilo** [comment]
I hope it was helpful. For now, I will close this issue.
Please, if you have any question feel free to reopen or open a new.
