### ISSUE TITLE
Normalize.css v.6.0.0 breaks input font-size styling

### ISSUE THREAD

**Issue by negativefix** [milligram/milligram#158]
It seems like some input element styles have been removed in version 6.0.0. Therefore, input font-size property is now inherited from user-agent styles.

Normalize v.5.0.0.
![screen shot 2017-03-29 at 15 47 58](https://cloud.githubusercontent.com/assets/1294467/24456166/d5065f14-149a-11e7-96f0-426e51de4832.png)

Normalize v.6.0.0.
![screen shot 2017-03-29 at 15 47 42](https://cloud.githubusercontent.com/assets/1294467/24456167/d509025a-149a-11e7-8fce-3927efcadefa.png)

**Comment by nateberkopec** [comment]
>Therefore, input font-size property is now inherited from user-agent styles.

Isn't that a problem with Normalize.css then?

**Comment by negativefix** [comment]
It is possible that it might be a problem with Normalize.css. I will open a ticket and report back.

**Comment by negativefix** [comment]
It seems like they removed all opinionated css rules from Normalize.css. See the commit [#649](https://github.com/necolas/normalize.css/pull/649).  Removed form element styles include the ones -such as `font-size`- that can be inherited from `body`.  Some of these rules can be included in milligram to provide consistent form styling with the rest of the framework.

**Comment by nateberkopec** [comment]
Huh, that's...intense. Your screenshot is still weird though, because the forms on https://milligram.github.io/forms.html look totally normal and I'm pretty sure they don't use normalize. So I still think this is not an issue with Milligram.

FWIW I use a far smaller CSS reset with Milligram: https://github.com/nateberkopec/speedshop/blob/master/_sass/mini-reset.sass

Milligram is ~9kb uncompressed/unminified, and Normalize is ~7.5kb. Using a CSS reset that's the same size as your framework is excessive in my view.

**Comment by negativefix** [comment]
[](https://milligram.github.io/forms.html) looks normal because it uses normalize.css 5.0.0. Check out the source. And since your reset shares styles in common with normalize.csss 5.0.0, it is possible that you are unaffected.

I agree with you that using normalize.css is overkill. But the size is not issue here. The issue is regardless of the reset I am using, will I be able to get the appearance advertised on milligram's site. I guess that is what is related to milligram.

**Comment by nateberkopec** [comment]
> I agree with you in that using normalize.css is overkill.

Yah that was just an aside.

I guess I agree with this issue. Maybe Milligram could incorporate a mini-reset, similar to the one I posted.

**Comment by cjpatoilo** [comment]
@negativefix congrats to the huge job! 
Thank you so much.

@nateberkopec you're right. It's time for a change normalize.css. I had worked on a new one, but I spent a lot of time away from Milligram. So I need to redo the necessary studies/tests to ensure that everything is okay.

btw, I bring news: Milligram v1.4.0 https://github.com/milligram/milligram/pull/244

Please, tell me if I can help you with something.
For now, I will close this issue.
