### ISSUE TITLE
Single file inclusion?

### ISSUE THREAD

**Issue by polterguy** [milligram/milligram#159]
Could I include a single file on my page to include milligram?

I see in the examples you have, that you also include normalize, in addition to some google fonts. Is there a way, to for instance build milligram yourself, such that it ends up with a single file inclusion? Possibly rely on system fonts instead of Google's, etc ...?

The reason why I am asking, is because I want to make sure I keep my number of HTTP requests as small as possible ...

The reason why this is important, is because I need a significantly better CSS framework than Bootstrap, and one of its requirements, is that it must run on **ridiculously small servers**, with **insanely small connections** ...?

Check out what I want to use it for [here](https://www.youtube.com/watch?v=3bEyBgI82OM).

**Comment by nateberkopec** [comment]
That's exactly how I use Milligram. In fact, I inline Milligram in the `head` tag. Example: https://www.speedshop.co/

**Comment by polterguy** [comment]
Thx :)
