### ISSUE TITLE
Buttons in website behaves strange.

### ISSUE THREAD

**Issue by SidKwok** [milligram/milligram#165]
http://milligram.io/

See social buttons:
<img width="352" alt="869b7455-8fe3-4d99-889f-234f2c07459f" src="https://cloud.githubusercontent.com/assets/13268747/25745846/727303ce-31d3-11e7-887c-f4eb3b764ae8.png">

chrome 58

safari and firefox behaves well.

**Comment by cjpatoilo** [comment]
Hi @SidKwok So Thank you for sharing this information. I'll check and see if this issue has anything to do with the new version of Google Chrome. I'm the last version, I just updated, see:

![image](https://cloud.githubusercontent.com/assets/1542831/25751917/01d31ad2-318d-11e7-8b74-63c74fbe7113.png)

![image](https://cloud.githubusercontent.com/assets/1542831/25751925/07833048-318d-11e7-81f5-aa4ffe3b0995.png)

**Comment by SidKwok** [comment]
I'm also 58.0.3029.96 (64-bit), it's kind of weird.
<img width="1194" alt="2017-05-05 23 23 29" src="https://cloud.githubusercontent.com/assets/13268747/25752152/f76720f4-31e9-11e7-9fc6-b22c91e78aed.png">
<img width="1194" alt="2017-05-05 23 24 00" src="https://cloud.githubusercontent.com/assets/13268747/25752156/f9ba167c-31e9-11e7-9498-9a41a087a819.png">

Is it related to the charset issue?

**Comment by nateberkopec** [comment]
@SidKwok my first guess would be something related to your locale. also what OS?

![screen shot 2017-05-05 at 9 39 48 am](https://cloud.githubusercontent.com/assets/845662/25752846/c506b02a-3176-11e7-8b45-16a0f92a11a0.png)

looks fine to me on Chrome stable and Canary.

**Comment by SidKwok** [comment]
@nateberkopec
macOS 10.12.4

It may be a locale issue.

**Comment by cjpatoilo** [comment]
@SidKwok I believe that this issue was resolved. Can you test for me?

**Comment by SidKwok** [comment]
Resolved
