### ISSUE TITLE
Add panel (bootstrap like)

### ISSUE THREAD

**Issue by freddi301** [milligram/milligram#168]
[bootstrap panel](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_panels&stacked=h)

**Comment by cjpatoilo** [comment]
@freddi301 
So I would like to extend Milligram to be more than 'a fast and clean starting point, with 2kb size'. 

I have huge plans for the future. Thank you for the idea.
For now, I will close this issue.
