### ISSUE TITLE
Question: Column widths

### ISSUE THREAD

**Issue by jonathanenlared** [milligram/milligram#171]
### Version info

Milligram v1.3.0
normalize.css v7.0.0

### Test case

I'm using this configuration:

|------------------------------Row-----------------------------|
|------Column40%---|---------------Column60%---------------|

https://codepen.io/anon/pen/YQPERa

### Expected behavior

I expected that in mobile the columns will collapse one after the other and take the whole width just like regular columns do. 

How I thought it will collapse:

MOBILE

|-----------------Row----------|
|------Column40%-------------|
|------Column60%--------------|

### Actual behavior
It works like a charm on big screens and tablets. 

The actual behavior is that the columns collapse one after the other BUT they don't use the whole width and there is a clear white space to the right.

How it collapse:

MOBILE

|-----------------Row----------|
|---Column40%-|
|------Column60%----|

**Comment by adamkolson** [comment]
Did anyone find a solution to this? Maybe I missed something, but it seems I'll need to add custom classes to resolve this.

**Comment by jonathanenlared** [comment]
I don't think so. But you could always extend milligram to better suit your needs. I play around with the media queries and it worked as a wanted it. Monkey patching mostly. 🐵

**Comment by sudheerDev** [comment]
@adamkolson u can resolve this by overriding existing column classes as well.

`@media (min-width: 40.0rem) {
  .column-1, column-2 {
    width: 100%;
  }
}
`

**Comment by dentonzh** [comment]
I ended up adding this to my css files, which better fits the expected behavior @jonathanenlared described:

```
@media (max-width: 40.0rem) {
    .row .column.column-10,
    .row .column.column-20,
    .row .column.column-25,
    .row .column.column-33,
    .row .column.column-40,
    .row .column.column-50,
    .row .column.column-60,
    .row .column.column-67,
    .row .column.column-75,
    .row .column.column-80,
    .row .column.column-90 {
        flex: 1 1 auto;
        max-width: 100%;
    }
}
```

Haven't tested it thoroughly yet, but seems to work under Chrome's mobile preview.
