### ISSUE TITLE
Does it really need normalize?

### ISSUE THREAD

**Issue by JulienJo** [milligram/milligram#172]
Hi!
The goal of milligram is to make small and fast website, isn'it it ?
So does it really need normalize?
Maybe something smaller like [minireset](https://github.com/jgthms/minireset.css) could do the job. 
Or maybe a cssreset is just usefulness because nearly everything is already in milligram.
What do you think?

**Comment by sparcut** [comment]
Maybe the option to choose would be a good option. 

I'd personally would like continue using normalize.css.

**Comment by cjpatoilo** [comment]
@JulienJo Great question!
I would like to know the reason to use another CSS Reset instead of normalize.css

**Comment by JulienJo** [comment]
@cjpatoilo as I said, if you to optimize speed, use least css (the purpose of milligram). So don't use something "big" like normalize.css. minireset.css is smaller. Or add some reset css in milligram (it already have some).

**Comment by cjpatoilo** [comment]
@JulienJo I understood you and you are right!  I have plans to remove normalize.css in the next version. For now, Milligram v1.4.0 will keep normalize.css@8.0.1

**Comment by cjpatoilo** [comment]
I will close this issue.
Please, if you need help feel free to reopen or open a new!
