### ISSUE TITLE
 the settings of class 'column column-X'

### ISSUE THREAD

**Issue by Mil00Z** [milligram/milligram#173]
It is possible to set a specific column like 'column column-X' ?
X = number of my choice between 1 to 100 ?

<div class="container">

  <div class="row">
    <div class="column column-10 " >column column-10 -> Col 10%
    </div>
  </div>
  <div class="row">
    <div class="column column-40 " >column column-40 -> Col 40%
    </div>
  </div>
  <div class="row">
    <div class="column column-70 " > column column-70 -> Col 70%
  </div>
  </div>
</div>
First and 2nd row take a good width, but the third row take100 % of the row.

THX a lot

**Comment by rmuratov** [comment]
Have you seen 'Column widths' [here](http://milligram.io/grids.html)?

**Comment by unip** [comment]
how about setting up the grid breakpoint according to screen size. E. g. like using `sm` `md` `lg` in bootstrap?

**Comment by cjpatoilo** [comment]
Hey @unip good call! My fear is to fill up a lot and leave heavy. Do you know any solution with Flexbox that is lightweight?
