### ISSUE TITLE
Gulp Watch...

### ISSUE THREAD

**Issue by labradorconnect** [milligram/milligram#175]
Hi there. 

I can't seem to figure out how to get gulp-watch to work so that when I update the SASS files in the SRC directory, that they are automatically updated in /DIST.

Any ideas? Thanks!

-Brian

### Version info

**Milligram:**

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**

**Comment by cjpatoilo** [comment]
Hey @labradorconnect maybe I can help you with this: http://ryanchristiani.com/getting-started-with-gulp-and-sass/

```
/* gulpfile.js */
import gulp from 'gulp'
import sass from 'gulp-sass'

gulp.task('styles', () => {
    gulp.src('./src/sass/**/*.sass')
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('./dist/css'))
})

//Watch task
gulp.task('default', () => {
    gulp.watch('./src/sass/**/*.sass', ['styles'])
})
```

**Comment by cjpatoilo** [comment]
@labradorconnect Let me know if this trick work for you?
