### ISSUE TITLE
Docs menu doesn't work when in any component page

### ISSUE THREAD

**Issue by fabienwang** [milligram/milligram#18]
in homepage 
http://milligram.github.io/index.html
the menu Docs works great, since anchors do exist in the page.

But when you go in any example page, let's say typography.html,
then the Docs menu fails since it tries to go to an anchor that is NOT in that page.

Hence, links in the Docs menu should always be related to index.html
like `/index.html#typography` instead of `#typography`

**Comment by cjpatoilo** [comment]
@fabienwang fixed! 
Thanks for the info.
