### ISSUE TITLE
Limit milligram's grid

### ISSUE THREAD

**Issue by alzearafat** [milligram/milligram#183]
Hi there!

I'm using version v1.3.0

How I can limit milligram's grid only by (just say) 3?
In Bootstrap, I just add something like this : `<div class="col-md-4">`, and it will only show 3 grids per row.

How I can achieve similliar result in milligram?

Any help would be greatly appreciated!
Thank you.

**Comment by lfsantana** [comment]
@alzearafat 

```html
<div class="row wrap">
    <div class="column column-33"></div>
    <div class="column column-33"></div>
    <div class="column column-33"></div>
    <div class="column column-33"></div>
    <div class="column column-33"></div>
</div>
```

```css
.row.wrap {
    flex-wrap: wrap;
}
```

**Comment by alzearafat** [comment]
Thanks a lot! @lfsantana

**Comment by cjpatoilo** [comment]
Hey @alzearafat @lfsantana There is a defined class for this [`.row-wrap`](https://github.com/milligram/milligram/blob/master/src/_Grid.sass#L30-L31)

```
<div class="row row-wrap">
    <div class="column column-33"></div>
    <div class="column column-33"></div>
    <div class="column column-33"></div>
    <div class="column column-33"></div>
    <div class="column column-33"></div>
</div>
```

**Comment by MentalGear** [comment]
> Hey @alzearafat @lfsantana There is a defined class for this [`.row-wrap`](https://github.com/milligram/milligram/blob/master/src/_Grid.sass#L30-L31)
> 
> ```
> <div class="row row-wrap">
>     <div class="column column-33"></div>
>     <div class="column column-33"></div>
>     <div class="column column-33"></div>
>     <div class="column column-33"></div>
>     <div class="column column-33"></div>
> </div>
> ```
> 
> @alzearafat Let me know if this worked for you?

This should be in the doc on grids, along with column-33. Guide is really lacking.
