### ISSUE TITLE
Navigation Component

### ISSUE THREAD

**Issue by danieldaeschle** [milligram/milligram#186]
What about adding toolbar/navigation component?

**Comment by cjpatoilo** [comment]
Hi @danieldaeschle Milligram will remain light and simple forever. 

However, in the future, I want to provide an extension of these features like toolbar, navigation, tooltips.. My doubts is about make use in this project or create a new.

**Comment by promatik** [comment]
@cjpatoilo I agree with you, milligram should be light forever.
I think the best way is to create an "extended" version of milligram, with a lot more components which you can be imported or not. The project should be the same.
