### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by mecurc** [milligram/milligram#187]

**Comment by dezudas** [comment]
I am working on one of my project using this as a boilerplate.

**Comment by nateberkopec** [comment]
I use this all of the time. Small, simple projects don't necessarily need releases every two weeks.

**Comment by DanielRuf** [comment]
But there are still many open issues and unmerged PRs. Some more maintainers would be definitely a good idea.

**Comment by cjpatoilo** [comment]
Guys, sorry for wait! I stayed out of Open Source projects for some time.. I'm coming back!

@nateberkopec you're right! @DanielRuf too. **In fact, Milligram has no huge issues** but there is so much to do and improve this experience: 

- Add CSS Variables
- Add CSS Grid Layout
- Snippet support for VSCode and Brackets 
- Enhance CLI support 
- Automate release 
- Add support for other FF frameworks 
- Improve Milligram's homepage with more samples
- In homepage, add showcase, mentions and customization area
- ..and much more!

I will dedicate the next months to attend all this and more. For now, I will review each PR and issue. Feel free to help me on this journey. ⭐️ 

@nateberkopec I'm very grateful for your attention, you have been contributing a lot. Thank you so much. 🙏  @dmitry-vakhnenko answering your question: Milligram is alive, more than ever! 🚀

**Comment by chuckreynolds** [comment]
any update from your last comment on here nearly a year ago @cjpatoilo ?  any status updates?

**Comment by dmitry-vakhnenko** [comment]
Looks like it dead.

**Comment by cjpatoilo** [comment]
> Small, simple projects don't necessarily need releases every two weeks.

Hi guys, 

This project is active and free of bugs. I recently developed some Open Source projects using Milligram like [Chalkboard](https://chalkboard.space) and [Airform](https://airform.io).

Currently I have not had much time to actively work on Milligram to improve features. So, the priority here is to fix any bug and incompatibility with any browsers. So, new features should come with time.

**Comment by yebo29** [comment]
Glad to hear!

**Comment by DanielRuf** [comment]
Well but CI builds fail =/

**Comment by TeraNovaLP** [comment]
@cjpatoilo Is a new release planned in the near future? I would appreciate it when the fixes were in a new Release build.

**Comment by DeathArrow01** [comment]
Another dead CSS framework. :(

**Comment by cjpatoilo** [comment]
Here is the PR for the new Milligram v1.4.0
https://github.com/milligram/milligram/pull/244

Thank you guys
For now, I will close this issue.
