### ISSUE TITLE
Grid behavior on mobile

### ISSUE THREAD

**Issue by dnohr** [milligram/milligram#188]
### Version info
- Milligram 1.3

### Steps to reproduce
```html
<div class="row">
<div class="column">test</div>
<div class="column column-20"">test 2</div>
</div>
```
### Expected behavior
I expected to see 100% width on the mobile grid, like other css frameworks are doing it.

### Actual behavior
The grid keeps the percentage width but on two lines, which looks strange.

### On Desktop
![Desktop](https://i.imgur.com/dnGRCXR.png)

### On Mobile
![Mobile](https://i.imgur.com/7nL5sgz.png)

Any solutions on it or is it the expected behavior?

**Comment by cjpatoilo** [comment]
Hey @dnohr Good call! 

I really liked the idea. In fact, I had already imagined something like that, but I'm not sure if everyone uses it that way. It would be interesting to map this information. Could you show me what CSS frameworks use 100% on mobile?

**Comment by dnohr** [comment]
Hi @cjpatoilo,

Seems like these frameworks are doing it:
- [MinCSS](https://mincss.com/)
- [Bulma](https://bulma.io/documentation/columns/sizes/)

I guess the solution would be to override the "column-20" width 100% if it's on mobile. Would it be possible?

Thanks for your work 👌🏻

**Comment by cjpatoilo** [comment]
@dnohr  I have found a way to add this support and maintain the current behavior. 👍  
Thanks for reporting this improvement.

**Comment by cjpatoilo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Grid behavior on mobile #188](https://trello.com/c/PmBKb8V5/72-grid-behavior-on-mobile-188)

**Comment by martinffx** [comment]
I'm having the same issue? How does one resolve this? On mobile I expect the grid to break the columns into row's

**Comment by salsadeveloper** [comment]
Can I fix this issue?

**Comment by cjpatoilo** [comment]
@celebritydeveloper this behavior was fixed. Look the demo:

![milligram-mobile](https://user-images.githubusercontent.com/1542831/82408403-e1332a80-9a41-11ea-8b4c-9e4572eddc21.gif)

**Comment by cjpatoilo** [comment]
@dnohr @martinffx For now, I will close this issue.
Please, feel free to reopen or open a new one.
