### ISSUE TITLE
Mobile resolution

### ISSUE THREAD

**Issue by prampec** [milligram/milligram#189]
### Version info
1.3.0

**Milligram:**
Firefox on Android

### Test case
Overall readability

### Steps to reproduce
Create a simple test page with normalize.css and milligram.css included.
Add `<main>` and `<section>` blocks to the page body, add some content (text, form with input fields).

### Expected behavior
Mobile version should have bigger page components (fonts, input fields) to compensate the smaller screen.

### Actual behavior
It seams that the mobile version is using the same pixel width/heght as the desktop one, but with a less smaller screen it just barely usable.

Interestingly enough the home page of the project https://milligram.io/ appears right on the mobile browser. So it might be a documentation issue: how to do it right?

**Comment by cjpatoilo** [comment]
@prampec I may be hasty, but I believe this issue evolves viewport settings:

```
<meta name = "viewport" content = "width = device-width, initial-scale = 1">
```

If that does not work let me know how wrote your HTML.

**Comment by prampec** [comment]
It did the trick. Thanks!
In this case I recommend creating a simple example page to guide others create minimal, still functional prototype. The problem with the provided examples, that they are not complete stand alone pages.
(Also note, that custom fonts are also optional. I use it for a smart device in AP mode, so all the content should be stored on the micro-controller, no online content can be accessed.)

**Comment by cjpatoilo** [comment]
@prampec Thank you for the tips.

There is a super simple boilerplate project with Milligram.
https://github.com/milligram/milligram-starter

**Comment by cjpatoilo** [comment]
For now, I will close this issue.
Please, if you need help feel free to reopen or open a new!
