### ISSUE TITLE
No outline with outlined-button

### ISSUE THREAD

**Issue by digitalhitler** [milligram/milligram#19]
Hello!
I am here just to say that `.outline-button` selector on example buttons page isn't really outlined:

![untitled](https://cloud.githubusercontent.com/assets/1048856/12190755/73af6d9a-b5dd-11e5-8ff2-a39f82bd3aa9.png)

But if I zoom-in browser, it's come back:

![screen shot 2016-01-08 at 07 55 08](https://cloud.githubusercontent.com/assets/1048856/12190749/58c61b64-b5dd-11e5-974a-e6a530db34ad.png)

```
Safari Version 9.0.2 (11601.3.9)
OS X 10.11.2
```

**Comment by cjpatoilo** [comment]
Hi @digitalhitler thanks for the info. Apparently this behavior with all browsers and not only with Safari. Anyway I will search to find more information about it.

**Comment by vkeusebio** [comment]
This is because of sub-pixel calculations on most web browsers and can be easily fixed by increasing the width of the border and it doesn't looks nice.

**Comment by cjpatoilo** [comment]
Note, the proportion of example in Safari is smaller than the other example shown. I have not found any articles that lists this behavior as a problem. Anyway I keep searching.

**Comment by vkeusebio** [comment]
@cjpatoilo check this out http://dieulot.net/css-retina-hairline

**Comment by slavanga** [comment]
Bootstrap had a similar issue recently.
https://github.com/twbs/bootstrap/issues/17812

The best way to fix this probably is using a px based border.

**Comment by cjpatoilo** [comment]
Sorry it took me so long to respond. I really do not see how a problem of the framework. This behavior is common, and is the way some browsers behave independently of the unit used. I've read several articles that talk about this issue and none of them solve this problem. 

BTW If someone finds a solution, please, feel the desire to send a PR so we can improve this problem. Anyway, thank you all for your contribution. For now I am closing this issue.
