### ISSUE TITLE
40rem grid don't reach iPhone 6/7 Plus

### ISSUE THREAD

**Issue by juanbrujo** [milligram/milligram#192]
### Version info

1.3.0

### Expected behavior

The grid must be 100% in iPhone 6/6 Plus, but they're not. Changing the @media from `40.0rem` to `42rem` works.

**Comment by sambhavsaxena** [comment]
Use percentage instead of sized units like Rem and Vh

**Comment by Shanna99** [comment]
can i work on this issue?

**Comment by sarmadhamdani02** [comment]
hi
Is this issue still open?

**Comment by juanbrujo** [comment]
5 years ago.. closing, seems this repository is dead.
