### ISSUE TITLE
File `src/_Table.sass` uses spaces in tabs

### ISSUE THREAD

**Issue by valentineus** [milligram/milligram#193]
### Version info

**Milligram:** 1.3.0

**Jekyll:** 3.7.3

### Actual behavior

```
Conversion error: Jekyll::Converters::Sass encountered an error while converting 'assets/css/milligram.sass':
                  Inconsistent indentation: 2 spaces were used for indentation, but the rest of the document was indented using 1 tab. on line 22
```

The Jekyll converter can not build the framework from the sources, because the source code uses tabs, and the `src/_Table.sass` file uses spaces.

**Comment by fadado** [comment]
I found a related bug:  the second half of the file `src/_Table.sass` has not be expanded into `dist/milligram.css`.

**Comment by cjpatoilo** [comment]
@valentineus you tried to use the code inside of the `dist` path?
