### ISSUE TITLE
dropwdown with multiple options is not fully usable

### ISSUE THREAD

**Issue by piever** [milligram/milligram#198]
I'm using Milligram including directly the css from:
```
 "//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic",
 "//cdn.rawgit.com/necolas/normalize.css/master/normalize.css",
 "//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css"
```

So far I'm loving this library but I've noticed a small issue with `<select>`. The normal case works fine but the case accepting multiple options, i.e. `<select multiple>`, looks very crowded and hard to use:

![multiple](https://user-images.githubusercontent.com/6333339/39831331-06cd2170-53bc-11e8-9573-3c57fa03f871.png)

**Comment by marcusasplund** [comment]
possoble solution; just add:

```css
select[multiple] {
  height: auto;
  background: none;
}
```
to your .css

**Comment by CoderSquirrel** [comment]
@marcusasplund wouldn't be good to add it on a pr?

**Comment by cjpatoilo** [comment]
@marcusasplund @schirrel Good call 🚀
