### ISSUE TITLE
Styles not preserved when printing/emulated print rendering

### ISSUE THREAD

**Issue by robsdudeson** [milligram/milligram#199]
### Version info
***Milligram:*** - latest via http://cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**
normalize.css - latest via http://cdn.rawgit.com/necolas/normalize.css/master/normalize.css
chrome - Version 66.0.3359.181 (Official Build) (64-bit) (Linux)

### Test case
https://codepen.io/robsdudeson/pen/ZoNgvP

### Steps to reproduce

Once navigated to the page
select print, print preview, or enable print render emulation

### Expected behavior

Styles in print view would more closely match those in screen view

### Actual behavior

Styles are not applied in the same way

### Normal rendering
![issue-199-no-emulation](https://user-images.githubusercontent.com/16904172/40501345-94b6ac6e-5f55-11e8-9e64-140117a7df3d.png)

### Print Rendering
![issue-199-print](https://user-images.githubusercontent.com/16904172/40501351-99259486-5f55-11e8-96e0-eb54ca922b1b.png)

**Comment by marcusasplund** [comment]
Use ```media="all"``` when linking css

```html
<link rel="stylesheet" media="all" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" media="all" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
    <link rel="stylesheet" media="all" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
```

See updated codepen here:
https://codepen.io/marcusasplund/pen/bKBmbo

**Comment by cjpatoilo** [comment]
@marcusasplund thank you for helping @robsdudeson 

@robsdudeson For now, I will close this issue.
Please, if you need help feel free to reopen or open a new!
