### ISSUE TITLE
Chrome warning [Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M67, around May 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

### ISSUE THREAD

**Issue by mukai11** [milligram/milligram#200]
### Version info
Milligram:1.3.0
Google Chrome: Version 66.0.3359.181 (Official Build) (64-bit)
OSX:10.12.6

### Steps to reproduce
Visit https://milligram.io/ by Chrome then open developer console.

### Expected behavior
No warnig.

### Actual behavior
The below warning is shown.

[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M67, around May 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

**Comment by adiramardiani** [comment]
Cause chrome have new standard for now
The css file use data:image to create svg file for dropdown menu, I think select/dropdown no need image for generate arrow icon @cjpatoilo

**Comment by promatik** [comment]
Hi everyone!
I just created a PR that solves this issue: #214, and it now uses the user `$color` variables.

**Comment by ItsPugle** [comment]
This can be closed as #214 fixes this :)

**Comment by ItsPugle** [comment]
This issue no longer occurs when visiting the site: 
![image](https://user-images.githubusercontent.com/22669894/60383313-8a7fd380-9ab2-11e9-9d70-2090dd85a9a7.png)

**Comment by mukai11** [comment]
@ItsPugle Thank you for your report. As one year has passed there is no warning message in Chrome. So this issue is no longer meaningless. I will close.
