### ISSUE TITLE
Table utils

### ISSUE THREAD

**Issue by schirrel** [milligram/milligram#207]
I'm aiming to add sobre extra classes to tables, so they look more charming

### Version info

latest

**Milligram:**

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**

### Expected behavior
Add hover effects, and condensed size, and primary header to the thable

**Comment by promatik** [comment]
@CoderSquirrel, you should do that in your code, what are your issues?

**Comment by CoderSquirrel** [comment]
yeah i done that in my code, but i really like the milligram appearence and tried to add something to 'look' or 'feel' cooler
i didn't know i couldn't

**Comment by cjpatoilo** [comment]
@schirrel @promatik [Milligram v1.4.0](https://github.com/milligram/milligram/pull/244) provides responsive table element. Besides, there is a plan to add another behavior in the table element for the next Milligram version.

**Comment by cjpatoilo** [comment]
@schirrel thank you for the idea.
For now, I will close this issue.
