### ISSUE TITLE
Firefox appearance 

### ISSUE THREAD

**Issue by schirrel** [milligram/milligram#210]
I've add support to `-moz-appearance`
 and `-webkit-appearance` once firefox shows in console a message about not supporting appearance
### Version info

latest

**Comment by promatik** [comment]
Milligram doesn't need to support browsers specific rules, that's webpack job.

**Comment by CoderSquirrel** [comment]
sorry about that but i didn't find any related abuot it on the contributing guide

**Comment by cjpatoilo** [comment]
@promatik thank you for helping @schirrel 

For now, I will close this issue.
Please, if you need help feel free to reopen or open a new!
