### ISSUE TITLE
Wrong spacing if rowspan is used

### ISSUE THREAD

**Issue by mapio** [milligram/milligram#217]
Take the example at https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics, more specifically the code at https://github.com/mdn/learning-area/blob/master/html/tables/basic/animals-table-fixed.html and point it to this css instead of the provided one.

You get (with the latest Firefox on OSX) what you see in the attached image, which is not correct (`Hen` and `Mare` seem to have some white-space to their left).

<img width="586" alt="screen shot 2018-11-09 at 16 36 03" src="https://user-images.githubusercontent.com/612826/48272041-ff2bd200-e43d-11e8-98fd-9ff9ee55579f.png">

**Comment by RamanaVem** [comment]
Is this still open? Can i take a look once?

**Comment by mapio** [comment]
Apparently yes, see the codepen https://codepen.io/mapio/pen/VwwzRrR (notice how "Mare" in the "Horse" row has a space in front of it, differently from "Stallion")

**Comment by RamanaVem** [comment]
hey @mapio i seen problem, where can i work this? can you make a Fork available in single html page?

**Comment by mapio** [comment]
I don't get you question and I'm not the mantainer of milligram… if you want to fix the bug, fork the repo and submit a pull request when done so that the repo owners can evaluate to accept it or not.

**Comment by Lisagrant101** [comment]
I opened a fork in this repo and submitted a pull request for my fix to this issue. 
Im new to GitHub and not sure if I did this correctly.

**Comment by Lisagrant101** [comment]
oh I think I did this wrong. I just realized I edited an example file not a milligram file.

**Comment by Lisagrant101** [comment]
Ok I edited the minimal.css file from the milligram repo and I will see if they accept it or not.
I added classes so that when using rowspan and colspan the alignment of words in the subsequent columns is not thrown off.

**Comment by mapio** [comment]
Nope… I'm not the repo owner, but those files look to be generated (have a look at https://github.com/milligram/milligram/blob/master/.github/contributing.md#building) starting from sass files under the `src` directory.

**Comment by cjpatoilo** [comment]
@mapio thanks for helping @Lisagrant101 

@mapio [here](https://codepen.io/mapio/pen/VwwzRrR) you forgot adding the normalize.css support.

Besides, it seems there is something wrong with your example if you copied from MDN. Note, in your example don't have `<thead>` and `<tbody>` elements.

**Comment by cjpatoilo** [comment]
@mapio thanks for helping @Lisagrant101 

@mapio [here](https://codepen.io/mapio/pen/VwwzRrR) you forgot adding the normalize.css support. 
Please, let me know if you still need help.

**Comment by mapio** [comment]
> @mapio [here](https://codepen.io/mapio/pen/VwwzRrR) you forgot adding the normalize.css support.

I've added it now, it seems not to change the status of the issue.

**Comment by cjpatoilo** [comment]
@mapio I can is wrong, but as I understand it: 

The problem is not when you use any attribute in this element but when you use the example structure: 

```html
  <table>
      <tr>
        <th>Animals</th>
      </tr>
      <tr>
        <th>Hippopotamus</th>
      </tr>
      <tr>
        <th>Horse</th>
        <td>Mare</td>
      </tr>
      <tr>
        <td>Stallion</td>
      </tr>
      <tr>
        <th>Crocodile</th>
      </tr>
      <tr>
        <th>Chicken</th>
        <td>Hen</td>
      </tr>
      <tr>
        <td>Rooster</td>
      </tr>
    </table>
```

Note, this behavior is generated by:

```css
td,
th {
  padding: 1.2rem 1.5rem;
}
td:last-child, 
th:last-child {
    padding-right: 0;
}
td:first-child,
th:first-child {
    padding-left: 0;
}
```

And even if you remove the attributes, there will still be "left white-space" in the same elements. Look: https://codepen.io/cjpatoilo/pen/yLYGQNy

**Comment by cjpatoilo** [comment]
@RamanaVem You can find the Table module here [`./src/_Table.sass`](https://github.com/milligram/milligram/blob/master/src/_Table.sass)

**Comment by cjpatoilo** [comment]
@mapio I can is wrong, but as I understand it: 

The problem is not when you use any attribute but when you use the example structure: 

```html
<table>
  <tr>
    <th>Animals</th>
  </tr>
  <tr>
    <th>Hippopotamus</th>
  </tr>
  <tr>
    <th>Horse</th>
    <td>Mare</td>
  </tr>
  <tr>
    <td>Stallion</td>
  </tr>
  <tr>
    <th>Crocodile</th>
  </tr>
  <tr>
    <th>Chicken</th>
    <td>Hen</td>
  </tr>
  <tr>
    <td>Rooster</td>
  </tr>
</table>
```

Note, this behavior is generated by:

```css
td,
th {
  padding: 1.2rem 1.5rem;
}
td:last-child, 
th:last-child {
    padding-right: 0;
}
td:first-child,
th:first-child {
    padding-left: 0;
}
```

And even if you remove the attributes, there will still be "left white-space" in the same elements. Look: https://codepen.io/cjpatoilo/pen/yLYGQNy

So, we need to find some solution to soften this behavior when there is this structure or remove this spacing by default in all table styles.

**Comment by mapio** [comment]
I'm not sure to get your point.  

My bug report is based on https://github.com/mdn/learning-area/blob/master/html/tables/basic/animals-table-fixed.html that (coming from MDN) I assume to be authoritative (even if it does not include `thead` and `tbody` elements, that are indeed optional as per HTML standard).

Unfortunately I'm no CSS expert and I can't fix the bug, or understand the reason why your CSS style makes it happen.

What is sure is that the above HTML example is valid and is rendered correctly unless you use your CSS style.

**Comment by cjpatoilo** [comment]
@mapio to fix the behavior in this specific example:

```css
th + td {
  padding-left: 0;
}
```

**Comment by cjpatoilo** [comment]
@mapio try to use:

```css
th + td {
  padding-left: 0;
}
```

This code fixes the "white-space" in this specific example.

**Comment by mapio** [comment]
If what you suggest is a fix, please implement it in the library and release a new version.

**Comment by cjpatoilo** [comment]
@mapio the code above is not the final solution for a possible fix. There are other ways to get the same result. Look: https://codepen.io/cjpatoilo/pen/bGVOQzd

So, to make changes in Milligram I need to understand better all scenes to ensure that expected behavior. I've been work on a new version v1.4.0. Let me see what I can do for this.

Thank you for your contribution and for reporting this example.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by mapio** [comment]
> Can I work on this issue?

I'm not the maintainer, but I can't see why you shouldn't!

**Comment by srishtij2000** [comment]
Okay

**Comment by tusharck** [comment]
hi @mapio , i made a PR for this issue, please review.

**Comment by mapio** [comment]
Dear @tusharck I'm not the maintainer of this project… for what it is worth, it seems that #274 fixes this bug, but I'm unable to accept PR for the project.

**Comment by tusharck** [comment]
Hi @cjpatoilo , as @mapio said, the PR #274 made fixes the issue, can you please review it.

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by TRIPATHISHIWANSHI** [comment]
Hello Sir,
I am new to Hactoberfest and I would like to contribute  to this project

**Comment by Yugalsaini123** [comment]
I am a beginner, can i also contribute to this project?

**Comment by shaaoni** [comment]
Hey @mapio Is this still open ? Then I want to contribute to it.

**Comment by Yugalsaini123** [comment]
I think, It was the previous years problem. Sent from Mail for Windows From: shaaoniSent: 07 October 2023 01:48To: milligram/milligramCc: Yugal Saini; CommentSubject: Re: [milligram/milligram] Wrong spacing if rowspan is used (#217) Hey @mapio Is this still open ? Then I want to contribute to it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by GitGuySu** [comment]
I am new to Hacktoberfest. If this issue is still open, I wanna contribute to this.

**Comment by mapio** [comment]
The last commit appears to be in 2020. This is probably an abandoned project. Not sure the maintainer will accept PRs.
