### ISSUE TITLE
Select style - inline SVG uses hardcoded colors

### ISSUE THREAD

**Issue by lmeysel** [milligram/milligram#222]
This is actually not a bug, but a recommendation: In _Forms.sass is the `select:focus`-selector, setting the select's background-image to native violet given in `$color-primary`. Using the interpolation-syntax, the variable could be referenced there, instead of using the hardcoded rgb-color, which helps when customizing the colors.

`data:image/svg[...]<svg[...]><path fill="#{$color-primary}" ...</svg>`

**Comment by RamanaVem** [comment]
Is this still open?

**Comment by lmeysel** [comment]
At least the code is not changed in the repository, therefore I'd say... yes.

**Comment by cjpatoilo** [comment]
@lmeysel Milligram v1.4.0 fix that. 
https://github.com/milligram/milligram/pull/244

For now, I will close this issue. 
Please, if you need help feel free to reopen or open a new!
