### ISSUE TITLE
Small proposal to have tags

### ISSUE THREAD

**Issue by ccomin** [milligram/milligram#223]
Hello,
Is it possible to have a tags functionality, on this principle : 
https://codepen.io/ccomin/details/YgPVWL

This is a functionality I would like to see in project
Bye

**Comment by CoderSquirrel** [comment]
@ccomin i've implemented this on pull request #230

**Comment by cjpatoilo** [comment]
@schirrel your job is very impressive! Thank you!

For now, I will close this issue.
Please, if you need help feel free to reopen or open a new!
