### ISSUE TITLE
Limit to 2 columns per row

### ISSUE THREAD

**Issue by ghost** [milligram/milligram#224]
### Version info
1.3.0

**Milligram:**

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**

### Test case

https://jsfiddle.net/y5tncd2f/2/

### Steps to reproduce
https://jsfiddle.net/y5tncd2f/2/

### Expected behavior

There should be 2 columns in a row as the class assigned to the div is column-50

### Actual behavior

4 columns are there inside a row outside the .container

**Comment by promatik** [comment]
@faizan47, your have 4 columns with `column-25` that behaviour is expected.
