### ISSUE TITLE
milligram.io/getting-started.html - should NOT be minified so that a user of a website could simply inspect what's going on the page and appreciate simplicity <EOM>

### ISSUE THREAD

**Issue by marsrobertson** [milligram/milligram#225]

**Comment by spapas** [comment]
Agreed! Or at least the unminified versions should be available somewhere.

Also the same should be done for the milligram web site; I had to clone the project from https://github.com/milligram/milligram.github.io and build the styles myself.

**Comment by cjpatoilo** [comment]
@marcusasplund You can see the source code of the website here  https://github.com/milligram/milligram.github.io

Now, I will close this issue
