### ISSUE TITLE
Pagination component

### ISSUE THREAD

**Issue by spapas** [milligram/milligram#227]
Any plans on adding a pagination component?

TIA,
Serafeim

**Comment by cjpatoilo** [comment]
Hi @spapas 

So I have some ideas on how to implement this, just not sure if I should put it directly into the main project or extend it elsewhere.

Also, I imagine adding something to the site to improve the user experience. What do you think?

**Comment by spapas** [comment]
Hello @cjpatoilo thank you very much, looking forward to it !

**Comment by CoderSquirrel** [comment]
@cjpatoilo it can be add as a task for hacktoberfest, what about?

**Comment by cjpatoilo** [comment]
@schirrel So I would like to extend Milligram to be more than 'a fast and clean starting point, with 2kb size'.

I have huge plans for the future. Anyway, thank you for the idea.
For now, I will close this issue.
