### ISSUE TITLE
Builds de PR falhando

### ISSUE THREAD

**Issue by schirrel** [milligram/milligram#229]
Esse não é uma issue sobre o projeto, mas sim sobre o ci.
Parece que todos os buildes de analise de de PR estão falhando por conta do node :/

**Comment by CoderSquirrel** [comment]
@cjpatoilo quando fiz a feature do pr #230 corrigi isso tambem

**Comment by cjpatoilo** [comment]
@CoderSquirrel Muito obrigado!

**Comment by cjpatoilo** [comment]
@schirrel CI working very well:
https://github.com/milligram/milligram/blob/release/v1.4.0

Thank you. Now, I will close this issue.
