### ISSUE TITLE
Hello- I am brand new to programming and I am stuck on how to use milligram. I tried to follow the outlined steps, but nothing happens. Why is milligram not getting applied to my styling?

### ISSUE THREAD

**Issue by klalchev** [milligram/milligram#242]
### Version info

**Milligram:**

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**

**Comment by szul** [comment]
It’s CSS. It’s applied automatically. How are you including it in your page?

**Comment by klalchev** [comment]
Well, I followed the instructions and installed milligram as outlined in
getting started. Then I copy/ pasted the three <link> provided in the head
of my html file and I was expecting that milligram will somehow style my
h1, button and form elements, but I think I am missing sth here, just not
sure what. I also downloaded the zip file and copied it in the folder of my
html file, but that also did not help...To give you an example I have a
button element- how do I apply on of the three button styles to my html
button? Do you have any videos for beginners?

**Comment by klalchev** [comment]
Below is my code snippet- I want to apply your styling to the button
element. When I run the code on codepen it is applying the correct style,
however, when I open the html file on my computer via my chrome browser, it
does not apply the styling- it just shows me a plain default button text.
Do I need to change the href and provide a path to the files on my
computer? That should not be the case since the files are hosted online,
though...Do you have an idea why I might be running into this issue? I want
to use your design system for my udacity project :)
 https://codepen.io/pen/

Thank you,
Kosta

**Comment by klalchev** [comment]
LOL! I figured it out!

when I load the html file locally into my browser, it is using the
file: protocol.
And since the milligram <link> has href="// without the http the browser is
attempting to load that one using the file: protocol.

Once I used the full URL (by adding http) everything worked as expected
applying your design!

Are there any videos that teach how to use milligram to its full potential?
This would be very helpful to me!

Thank you,

Kostadin

**Comment by szul** [comment]
Were you using the CDN links or a downloaded copy for that? What browser are you using? The lack of a prefixed `http` or `https` means that the browser will load the URL using whichever protocol is used for the page itself.

There are no videos that I'm aware of, but the web site gives an easy over of what get altered when you use the styles.

**Comment by klalchev** [comment]
I used the CDN links. I also downloaded the folder- why do I need the
folder if I can use the links to render the information? Just curious.
Also- I installed milligram on my computer using the below function, but I
am not sure what it does.
$ npm install milligram
I also followed your other instructions: $ npm install -g milligram-cli,
$ milligram init new_app
$ cd new_app $ npm start

and it seems like it got installed, but I am not sure what it is supposed
to do and how I can use the milligram functionality.
Is there an interface involved with milligram or do I just have to enter
the code snippet and milligram will apply the corresponding style?
For example when I enter this code in my html: <a class="button"
href="#">Default
Button</a> - I get your default button with purple background,
so I guess it is working, but is there more to it that I am not util

Thank you and sorry for wasting your time with my nonsense...
Kosta

**Comment by marcogargano** [comment]
@klalchev 
Check this: https://codepen.io/marcogargano/pen/pojKMdo

**Comment by galiprandi** [comment]
Could you solve your problem?

**Comment by klalchev** [comment]
Yes. all good now

**Comment by cjpatoilo** [comment]
@szul @marcogargano @galiprandi 
I'm very happy. Thank you for helping @klalchev 

@klalchev If you need something feel free to open a new issue.
Now, I will close this issue.
