### ISSUE TITLE
Colum-33 not going to next row automatically.

### ISSUE THREAD

**Issue by squidoan** [milligram/milligram#247]
Hello,
Greetings. 

I am trying milligram - great work. 

I've 8 columns in a row with "column column-33". 
But it is showing only 3 of it on the container. others have just vanished. but on inspect- it's ok - the content is there. 

It should automatically go to new row after 3 columns. 

How can I do that?

**Comment by squidoan** [comment]
Maybe it will solve : 
.row {
	flex-flow: row wrap; 
}

Any idea or help? 
thanks

**Comment by okeken** [comment]
Can you share a snippet of your mark-up?

**Comment by cjpatoilo** [comment]
@okeken thank you for your attention. 

@squidoan please, let me see your code. You can add your code here or on codepen.io.

**Comment by cjpatoilo** [comment]
@squidoan Now I will close this issue. 
Please, feel free to reopen this issue or open a new one if you need any help
