### ISSUE TITLE
CDN link broken

### ISSUE THREAD

**Issue by swalberg** [milligram/milligram#250]
### Version info

**Milligram:** Latest (From CDN)

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**

### Test case

Using the link from the "Getting started" page: cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css, it's a 404.

### Steps to reproduce

1. Install Milligram via CDN links in the getting started guide
2. Observe that Milligram CSS is a 404

### Expected behavior

A 200 followed by the CSS for milligram

### Actual behavior

A 404

It looks like `/dist` was removed from this repo some time ago but rawgit.com only finally purged it from cache. I'm not sure when since this is on a site I don't look at much, maybe within the last month.

For CDNs, rawgit.com is also going away. The rawgit.com page lists some alternatives.

**Comment by dohliam** [comment]
It looks like the `dist` folder was removed in [this commit](https://github.com/milligram/milligram/commit/af339b2c054bf92b0a5300e671e5d18151229ea5) on June 1.

@cjpatoilo is there any chance you might consider restoring the `dist` folder with the (minified and unminified) CSS source at some point in the future? (For what it's worth, this also broke our ability to update milligram automatically at [dropin-minimal-css](https://github.com/dohliam/dropin-minimal-css).)

**Comment by cjpatoilo** [comment]
@swalberg @dohliam 

Please, can you review this pull request https://github.com/milligram/milligram/pull/251

**Comment by dohliam** [comment]
@cjpatoilo Thanks so much for the quick fix! It's great to have the compiled CSS available again. :+1:

**Comment by swalberg** [comment]
Thank you! Looking forward to seeing this merged!

**Comment by cjpatoilo** [comment]
@swalberg @dohliam it's my pleasure to rollback the Rawgit support. So, I just didn't know that there was this problem. I love Rawgit and @rgrove made the huge work.

**Comment by cjpatoilo** [comment]
@swalberg @dohliam all done! Now I will close this issue and if you have any questions, please, feel free to reopen this issue or open a new one.
