### ISSUE TITLE
remove dist/ from repo. add Travis-CI

### ISSUE THREAD

**Issue by ghost** [milligram/milligram#28]
As i see a lot of PR changing dist/ css files. I suggest to simply drop them from the repository.

You could also a continuous integration like Travis-CI so it could automatically create a release (using gulp or grunt) you could automatically get that release overwritten with every commit on your master branch.

Just a suggestion.

**Comment by hedii** [comment]
+1

or PR only to a dev branch (which has to be created), and compile to dist each time on the dev branch.
That way the master dist is not changed at each PR

**Comment by cjpatoilo** [comment]
You're right, it really is difficult to see what has changed.

**Comment by sudheerDev** [comment]
@cjpatoilo you can create different active branch for package managers. something in the lines of https://github.com/chinmaymk/angular-charts/issues/45 might also work

**Comment by cjpatoilo** [comment]
@hedii @sudheerDev I'm not really sure how I could do it, but I would add this feature in Milligram. @willianjusten suggested to using Git Hooks #108, so there will always be updated `dist` covering any forgotten about it.

**Comment by sudheerDev** [comment]
@cjpatoilo yes when you have git hook we can ignore dist using .gitignore!

**Comment by cjpatoilo** [comment]
@sudheerDev Husky can prevent bad commit, bad push and other stuff like that.

**Comment by sudheerDev** [comment]
@cjpatoilo ignore earilier comment. I need to know a way to generate and maintain dist without users updating it through commit. If i fond out something i will give a pull request

**Comment by cjpatoilo** [comment]
Guys @hedii @sudheerDev Have you found any solutions to improve this?

**Comment by cjpatoilo** [comment]
Guys, for now I will close this PR. Feel free to reopen this issue if you find any solution.
