### ISSUE TITLE
no style for disabled input

### ISSUE THREAD

**Issue by vkeusebio** [milligram/milligram#29]

**Comment by cjpatoilo** [comment]
You tested direct downloading from the repository or from a package manager? 
These features will come in version 1.1.0

**Comment by vkeusebio** [comment]
I always pull the source from the master branch and compile on my own.

**Comment by vkeusebio** [comment]
I always pull the source from the master branch and compile on my own. @cjpatoilo I'll send a PR

**Comment by vkeusebio** [comment]
that was funny, just fetched the latest commits from master. Disabled button works fine now but it seems that milligram on CDNjs isn't updated.
