### ISSUE TITLE
Scroll to top arrow button

### ISSUE THREAD

**Issue by vaishnav-sh** [milligram/milligram#290]
Adding a scroll to top button on the documentation page.

**Comment by vaishnav-sh** [comment]
Please assign me this issue. I would like to contribute as a part of hacktoberfest

**Comment by abhinandant34** [comment]
I can do this task

**Comment by gokul5102** [comment]
Please assign this issue to me

**Comment by Sudipta2002** [comment]
Assign this to me I can do this
