### ISSUE TITLE
textarea rows can's set attrubtes  rows 

### ISSUE THREAD

**Issue by tablecell** [milligram/milligram#294]
### Version info

**Milligram:**
1.4.1
**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**
firefxo 68  
win7-x64
### Test case

````html
<!doctype html><html><head>
		<link rel="stylesheet" href="dist/milligram.min.css" />
 </head><body>
		
		<textarea rows="15" > </textarea>

</body></html>
```

<!-- Provide code samples on [Codepen](http://codepen.io/). -->

### Steps to reproduce

<!-- Provide the steps needed to reproduce the issue given the above test case. -->

### Expected behavior

<!-- What is the expected behavior? -->
textarea rows  -> 15 
### Actual behavior
textarea not changed 
<!-- What is the actual behavior? -->

**Comment by shubhrastogi07** [comment]
I would like to work on this issue
please assign it to me

**Comment by jeeljain19** [comment]
I would like to work on this issue
please assign it to me @tablecell 
Thank you in advance!

**Comment by tablecell** [comment]
> 
> 
> I would like to work on this issue please assign it to me

 Assignees
No one assigned    Assignees is not clickable

**Comment by abhiraj-kale** [comment]
> ### Version info
> **Milligram:** 1.4.1 **Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):** firefxo 68 win7-x64
> 
> ### Test case
> ```
> <!doctype html><html><head>
> 		<link rel="stylesheet" href="dist/milligram.min.css" />
>  </head><body>
> 		
> 		<textarea rows="15" > </textarea>
> 
> </body></html>
> ```
> 
> 
> 
> ### Steps to reproduce
> 
> 
> 
> ### Expected behavior
> 
> 
> textarea rows  -> 15 
> ### Actual behavior
> textarea not changed 
> 
> ```

add this css for the textarea 
textarea { height: auto; }
