### ISSUE TITLE
Forms: select box is unstyled

### ISSUE THREAD

**Issue by slavanga** [milligram/milligram#3]
The default select styles get removed by ```appearance: none``` but no custom styles are in place.

![select](https://cloud.githubusercontent.com/assets/1077807/12064576/910e800a-afc6-11e5-8a00-dfb2b28b55a5.jpg)

**Comment by vkeusebio** [comment]
isn't the default style for the options dependent on the user's operating system?

**Comment by slavanga** [comment]
That's true but right now the default style is removed entirely and not replaced. The select box looks like a normal input field in Firefox and webkit based browsers.

**Comment by cjpatoilo** [comment]
Hi @slavanga. This feature has been improved [c88d81a](https://github.com/milligram/milligram/commit/c88d81a23a50c8c02d9588006c8e01e210960606)
Thanks a lot.
