### ISSUE TITLE
[Improvement] Dark Mode

### ISSUE THREAD

**Issue by nsde** [milligram/milligram#308]
Hey there,
I'd love to see official dark mode support, just like so:

```css
@media (prefers-color-scheme: dark)
```

This means that visitors who set "dark mode" on their computer/browser settings will get a dark design automatically without having to click anything.

If this something that can't/shouldn't be made, is there any other way I can apply dark mode to my Milligram.css-website? Should I use a fork of Milligram? If so, which?

Kind regards

**Comment by Sarveshk76** [comment]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/78719645/144356500-960414ce-16a0-4a54-802e-1ce25effd39d.png">
<img width="901" alt="image" src="https://user-images.githubusercontent.com/78719645/144356585-5a643eed-39e2-4945-a981-b1f82d06d49c.png">

**Comment by Sarveshk76** [comment]
I've made the changes as per the suggestions given above, please give feedback if anything needs to be changed.

**Comment by Jieiku** [comment]
Nice! Thank you!

**Comment by plaffitt** [comment]
Is there any news about this feature?

**Comment by Jieiku** [comment]
I dont think milligram is maintained anymore, I ended up trying a few frameworks before writing my own.

You could always fork milligram and make it your own, otherwise here is a list I made: https://github.com/Jieiku/classless-css/blob/master/README.md

**Comment by nsde** [comment]
Milligram isn't maintained. With that being said, closed.
