### ISSUE TITLE
change in docs

### ISSUE THREAD

**Issue by BoDonkey** [milligram/milligram#31]
The typography web page has a typo. 
I believe:

<a>Archor</a>

should be
 <a>Anchor</a>

I don't think I can edit the actual doc pages-maybe I'm wrong.

**Comment by fabienwang** [comment]
You are wrong indeed.

https://github.com/milligram/milligram.github.io/blob/master/typography.html#L115

;)

**Comment by cjpatoilo** [comment]
Hello @BoDonkey. Thanks for the info!
