### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by Lambdac0re** [milligram/milligram#316]
I was using "dhg/Skeleton" before which is absolutely abandoned. 
Has this project the same fate? The last commit was Jun 18, 2020...
If so, what other minimal boilerplate do you use?

**Comment by cjpatoilo** [comment]
I'm working on v1.5.0 to be launched ASAP. Besides, I wish to launch v1.6.0 still this year.

**Comment by christophdoering** [comment]
Good to hear looking forward to it.

**Comment by Tragio** [comment]
@cjpatoilo would be possible to have it in a branch and see how can we contribute to it? 🙂
