### ISSUE TITLE
Footer needs to be styled

### ISSUE THREAD

**Issue by Dikshatomarr** [milligram/milligram#333]
![image](https://user-images.githubusercontent.com/91546745/195928035-df7925ca-49bb-4ec4-8ede-b69163936026.png)

These following Changes Could be performed, and I am willing to work on this issue.

- space can be decreased and a 
- dark background color can be added in footer.

**Comment by thesakshidiggikar** [comment]
Hello! I would like to work on this issue can you please assign this work to me?

**Comment by Sandeepkr43** [comment]
footer can be styled by using the CSS property 
I would like to contribute to this issue.
so, I request you to assign this issue to me.

**Comment by xoshiraghavx** [comment]
i can do this

**Comment by HimanshiChainani** [comment]
I want to fix this issue could you please assign this tak to me

**Comment by soham999a** [comment]
I want to fix this issue, I have made that kind of issue previous also

**Comment by neonfuz** [comment]
Sorry to be off topic, but why is there such a sudden interest in contributing to this repo, specifically mostly people from India? Is there some sort of class or incentive going on to contributing to this repo? I followed this repo for years with no notifications, in the last year or so there are hundreds of new PRs, clearly something is going on here

**Comment by zelfroster** [comment]
> Sorry to be off topic, but why is there such a sudden interest in contributing to this repo, specifically mostly people from India? Is there some sort of class or incentive going on to contributing to this repo? I followed this repo for years with no notifications, in the last year or so there are hundreds of new PRs, clearly something is going on here

This was at the time of Hacktoberfest. That's the reason I think.
Also, people are being more aware about Open Source Contributions in general.

**Comment by jaiakash** [comment]
> Sorry to be off topic, but why is there such a sudden interest in contributing to this repo, specifically mostly people from India? Is there some sort of class or incentive going on to contributing to this repo? I followed this repo for years with no notifications, in the last year or so there are hundreds of new PRs, clearly something is going on here

The reason is the popularity of Hacktoberfest and GSoC. 
Students in India are getting more aware of open-source and remote work. Especially since the last 1-2 years.
