### ISSUE TITLE
Correct spelling mistakes and minimize gaps

### ISSUE THREAD

**Issue by jgyfutub** [milligram/milligram#386]
Hi this is vedant pandey and i am looking forward to contribute in the milligram repository.While scrolling the website I found that gaps between subtopics is way too much.Thus I am interested in solving this issue.Thus I request to please assign this issue to me under hacktoberfest 2023

![Milligram - A minimalist CSS framework and 2 more pages - Personal - Microsoft​ Edge 03-10-2023 19_19_06](https://github.com/milligram/milligram/assets/97391064/1c675066-5119-49b8-9b21-b71dbc90244f)

**Comment by dev7n** [comment]
Can it will be assigned to me ?

**Comment by Advaitkhadye** [comment]
Hello,
can you assign this issue to me?

**Comment by venunaik509** [comment]
hii,
will you assign this work for me !!!!
