### ISSUE TITLE
 few suggestions

### ISSUE THREAD

**Issue by vujovicigor** [milligram/milligram#39]
Great work guys, milligram is fantastic.
Here is few suggestions:
- when select element is open, default browser color is used, it can be fixed:
```
option:checked
	background: linear-gradient($color-primary, $color-primary)
```

- onclick effect:
```
.button:active, button:active, input[type="button"]:active, input[type="submit"]:active, input[type="reset"]:active
	transition: none
	opacity: 0.7
```

- some transitions:
```
.button, button, input, textarea, select
	transition: border 0.3s, background-color 0.3s, color 0.3s
```

- responsive img:
```
img
	height: auto
	max-width: 100%
```

- media query to reset max-width on small screen devices:
```
// Smaller than mobile screen
@media (max-width: 40.0rem)
	.row
		flex-direction: column
		.column
			max-width: 100%

		.column
			&.column-10, &.column-20, &.column-33, &.column-34, &.column-40, &.column-50, &.column-60, &.column-66, &.column-67, &.column-75, &.column-80, &.column-90
				max-width: 100%

```

here is example:
http://codepen.io/vujovichigor/pen/NxvoOR
(try resizing browser)

Thank you for milligram :)

**Comment by cjpatoilo** [comment]
@vujovicigor Thanks for the suggestions, some have already been submitted, I will be providing other and they become available in the next update. =D
