### ISSUE TITLE
Links have target "blank" instead of "_blank"

### ISSUE THREAD

**Issue by rrrene** [milligram/milligram#40]
Hi CJ,

good job on the visuals! :clap: 

Unfortunately, all links that *should* open in a new tab/window have the attribute `target=blank` instead of `target=_blank`. For something that is concerned with professional web development this is a bit odd. In case you're wondering what I'm talking about [have a look at this page](http://www.w3schools.com/tags/att_a_target.asp) explaining the meaning of `_blank`.

As I said, love the visuals and minimalist style, this is just meant as a "heads up" :+1:

**Comment by joaobarbosa** [comment]
Done :+1:

**Comment by cjpatoilo** [comment]
@rrrene Thanks for the contribution
