### ISSUE TITLE
Styling Rows and Columns

### ISSUE THREAD

**Issue by warthogweb** [milligram/milligram#45]
I would like to do some simple styling such as top/bottom margin, borders etc. to these. The styles I am adding are having no effect when I put them where I think they should go. Any help would be much appreciated.

Martin

**Comment by cjpatoilo** [comment]
Hi @warthogweb You need to show how you are doing it so I can help you. You could submit your code to some services like [Codepen](http://codepen.io/)

**Comment by warthogweb** [comment]
Thanks - I have organized the row styles. But, can I have milligram full 
width??

Martin

On 24/01/2016 20:21, CJ Patoilo wrote:
>
> Hi @warthogweb <https://github.com/warthogweb> You need to show how 
> you are doing it so I can help you. You could submit your code to some 
> services like Codepen <http://codepen.io/>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/milligram/milligram/issues/45#issuecomment-174326858>.Web 
> Bug from 
> https://github.com/notifications/beacon/AKfnCKTtSSE5oAzyTOIzKpXMAMUogzPXks5pdQ2egaJpZM4HGTaO.gif
>

-- 
Best Regards,
Martin

	


      Durban Web Design

www.warthog.co.za <http://www.warthog.co.za>

084 432 5907

031 465 7781

**Comment by voodah** [comment]
@warthogweb You can override your '.container' and set max-width: 100%, the columns inside will adapt automatically.

Make sure to check that your media queries are also behaving like you want.

**Comment by warthogweb** [comment]
Thanks - I put together a sample with some free scripts for a student - 
sticky menu, megamenu etc.

zulu-culture.co.za/mg <http://www.zulu-culture.co.za/mg>

Martin

On 25/01/2016 20:17, voodah wrote:
>
> @warthogweb <https://github.com/warthogweb> You can override your 
> '.container' and set max-width: 100%, the columns inside will adapt 
> automatically.
>
> Make sure to check that your media queries are also behaving like you 
> want.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/milligram/milligram/issues/45#issuecomment-174608559>.Web 
> Bug from 
> https://github.com/notifications/beacon/AKfnCIQ9Kl5UyNfBAKOrSofVqLvuAYttks5pdl4hgaJpZM4HGTaO.gif
>

-- 
Best Regards,
Martin

	


      Durban Web Design

www.warthog.co.za <http://www.warthog.co.za>

084 432 5907

031 465 7781

**Comment by cjpatoilo** [comment]
@warthogweb You found the answer to your question?

**Comment by elad** [comment]
@cjpatoilo I think he wants `.container-fluid`, that spans the full width of the viewport. Wouldn't hurt to add.

**Comment by Mortiferr** [comment]
@warthogweb That link doesn't work.

**Comment by jackmcpickle** [comment]
My new PR https://github.com/milligram/milligram/pull/101 enables you to change the container max-width by setting the `$container-max-width` variable.

**Comment by cjpatoilo** [comment]
@jackmcpickle He did not need to edit variables to solve this CSS problem. He just needs to overwrite the class `.container` setting the property `max-width: 100%`.

@warthogweb Let me know if you solved your problem, for now I will close this issue but nothing prevents re-open it later.
