### ISSUE TITLE
Adding more css utilities 

### ISSUE THREAD

**Issue by rajzshkr** [milligram/milligram#49]
It is better to have utilities when developing a frameworks, we can have more utilities like center, ellipsis, textNoWrap, textTruncate and much more. looking to give a pull request.

**Comment by cjpatoilo** [comment]
Hi @rajzshkr 
Note, Milligram use few classes to provides a minimum configuration of styles for a quick and clean starting point. Just it! I'm closing your request and I appreciate their efforts to improve this project. 
Thanks a lot.
