### ISSUE TITLE
Framework Customization

### ISSUE THREAD

**Issue by ivandinizaj** [milligram/milligram#5]
Since the large differential of framework is to be as light as possible, it would be convenient to have a customization tool. So, the developer can choose which items from framework they need to download separately (Buttons, Typography, Codes, Tables, Blockquotes ...). Therefore, framework would be more objective and, consequently, faster.

**Ex:** http://globocom.github.io/bootstrap/customize.html

**Comment by kevinthomas-dev** [comment]
That would definitely be a good feature. Hope they update the framework soon.

**Comment by alisonmonteiro** [comment]
Would be a good feature, @ivandinizaj :+1:

**Comment by cjpatoilo** [comment]
Guys, about this feature, what do you think: is better to add this functionality directly on the site or create a new side project?

**Comment by fabienwang** [comment]
@cjpatoilo on the site directly.

**Comment by vkeusebio** [comment]
@cjpatoilo on the site.

**Comment by abouthiroppy** [comment]
on the site. :+1:

**Comment by kevinthomas-dev** [comment]
@cjpatoilo on the site.

**Comment by cmnstmntmn** [comment]
i belive this is a pain in the ass, since most of us use it from sources (.scss files) with a task runner webpack/gulp. so it's easy not to include any of (buttons, blockquotes ..) in the **miligram.sass** in order to have an optimized output.

**Comment by cjpatoilo** [comment]
Hi @cmnstmntmn Milligram has specific versions for this use

 [milligram-stylus](https://github.com/milligram/milligram-stylus)
 [milligram-less](https://github.com/milligram/milligram-less)
 [milligram-sass](https://github.com/milligram/milligram-sass)
 [milligram-scss](https://github.com/milligram/milligram-scss)

**Comment by cjpatoilo** [comment]
@cmnstmntmn Milligram already has support for this use. I created other repositories in parallel to support some preprocessors beyond Sass (source code). Unfortunately I have not had time to update the homepage with this information. 

BTW, thanks for the suggestions.

**Comment by voylinux** [comment]
How about having most values like sizes (not only colors) in a variables file?.
It would be easy in case you need to overwrite any value in your project without adding extra declarations.

How do you feel about it?
I could prepare a pull request with some of those.

**Comment by cjpatoilo** [comment]
@voylinux Thankful for disposal. There are requests about this feature, the idea is amazing. I'd love to receive your contribution as well as their opinion on these submissions.

#101
#105

**Comment by cjpatoilo** [comment]
BTW about this "Framework Customization", we will soon least provide a section for this feature. 
For now I will close this issue.
