### ISSUE TITLE
Sass files not available via NPM

### ISSUE THREAD

**Issue by jonjaques** [milligram/milligram#51]
Would be good to ship the source files with npm so they can be easily imported into existing projects. :smile:

**Comment by cjpatoilo** [comment]
Hi @jonjaques 
Milligram has some versions available for [Stylus](https://github.com/milligram/milligram-stylus), [Sass](https://github.com/milligram/milligram-sass), [Less](https://github.com/milligram/milligram-less).. 

Thank you for asking though
