### ISSUE TITLE
Rendering issues on Windows Phone 8.1

### ISSUE THREAD

**Issue by cglong** [milligram/milligram#52]
I noticed several rendering issues on the most recent version of Windows Phone 8.1 (8.10.15148.160 on a Lumia 830). Screenshots attached :) Thanks!

![wp_ss_20160123_0002](https://cloud.githubusercontent.com/assets/137214/12533800/e143af2c-c1f1-11e5-900b-56e202f14817.png)
![wp_ss_20160123_0003](https://cloud.githubusercontent.com/assets/137214/12533803/e144b8d6-c1f1-11e5-85f2-c91762b74854.png)
![wp_ss_20160123_0004](https://cloud.githubusercontent.com/assets/137214/12533802/e1445f30-c1f1-11e5-84ce-789ad6bd6095.png)
![wp_ss_20160123_0005](https://cloud.githubusercontent.com/assets/137214/12533801/e143fe96-c1f1-11e5-90a0-3b23b039ca9b.png)

**Comment by cjpatoilo** [comment]
Hi @cglong Lately I have had some support issues with the new Microsoft browser. I will further consider the possible to keep that best supported browser. Thanks for the info.
