### ISSUE TITLE
Publish source to NPM

### ISSUE THREAD

**Issue by niallobrien** [milligram/milligram#58]
Hi, when I pull in Milligram via `npm`, I don't have a `src` directory which is far from ideal. Can you publish the `src` directory to `npm` please? Thanks.

**Comment by cjpatoilo** [comment]
Hi @niallobrien Let me understand why I should keep the`src` folder in the download.

**Comment by niallobrien** [comment]
Because I would like to import `milligram.sass` into my own `.sass` file and have access to the same variables as those defined by Milligram.

**Comment by cjpatoilo** [comment]
Oh sure, to this I thought to keep other projects in parallel, check this out: 
[milligram-less](https://github.com/milligram/milligram-less)
[milligram-sass](https://github.com/milligram/milligram-sass)
[milligram-stylus](https://github.com/milligram/milligram-stylus)

**Comment by niallobrien** [comment]
Ah, you should probably include those in the docs. :)

**Comment by cjpatoilo** [comment]
Of course, I'm bringing great news for the next version and with them this information. I appreciate their efforts to improve this project. For now I'm closing this issue.
