### ISSUE TITLE
Why do <button> need the class .button?

### ISSUE THREAD

**Issue by franciscop** [milligram/milligram#60]
My question is basically [this question](http://stackoverflow.com/questions/34996818) that is too opinionated for SO:

**Why do the element `<button>` need the class `.button` to have that style?**

I understand that `.button` is useful to style, say, anchor tags as buttons `<a class="button">`, but why didn't you design the element `<button>` from the ground up to have the same style? Like this:

```css
button, input[type="submit"], .button {
  /* button styles */
}
```

**Comment by cjpatoilo** [comment]
Hi @franciscop 

I do not know why Milligram was quoted this example. If you look at the close source you will realize that it does not depend on class `.button` to style element `<button>`. You must be wondering why I kept this example on the site. Well, that went unnoticed.

shotscreen
![image](https://cloud.githubusercontent.com/assets/1542831/12568222/0e0160a6-c3a3-11e5-933f-8de560213080.png)

**Comment by franciscop** [comment]
Oops I totally missed that. I went through the documentation of several CSS libraries that I knew to check it, but I didn't dig into the code, sorry about that and thanks for the answer! :+1:
