### ISSUE TITLE
Similarity to Skeleton

### ISSUE THREAD

**Issue by voodah** [milligram/milligram#61]
Everything looks very similar to Skeleton (http://getskeleton.com/). 

Did you take some inspiration from them?

**Comment by cjpatoilo** [comment]
Hi @voodah 

Skeleton is a awesome reference but if look at the code you will see that the resemblance is related apelas by simplicity of design. 

See this article, I'll tell him more about how this project began.
https://medium.com/@cjpatoilo/milligram-a-minimalist-css-framework-e0496aea8167#.qaab27kgz
