### ISSUE TITLE
npm/bower ignore "src" folder

### ISSUE THREAD

**Issue by Findus23** [milligram/milligram#64]
Is there any reason for ignoring the "src" folder in package.json and bower.json?
I am a beginner, but I thought it is common to include the source files (Sass) in the bower/npm package. 
E.g. Bootstrap: https://github.com/twbs/bootstrap/blob/master/bower.json

I hope you can help me.

**Comment by cjpatoilo** [comment]
Hi @Findus23 
This [thread](https://github.com/milligram/milligram/pull/55) might clarify your question. If I can help with anything else feel free to open a new question. For now I'll close this issue.

**Comment by Findus23** [comment]
Oh, I'm sorry. I totally missed that pull request.
