### ISSUE TITLE
Media query + rem documentation is incorrect

### ISSUE THREAD

**Issue by alexiscordova** [milligram/milligram#65]
Found the framework linked through the HTML5 Weekly newsletter, and it looks pretty great. However, I found one issue with the media query documentation (http://milligram.github.io/tips.html).

`rem` units in media queries are relative to the initial value of `font-size` on the `html` element, not the declared value (http://www.w3.org/TR/css3-mediaqueries/#units). So in essence, `em` and `rem` units in media queries behave the same, and are based on `16px`. `40rem`, in this instance, doesn't equal `400px`; it equals `640px`.

You can see an example here: http://codepen.io/acordova/pen/LGmNGP

**Comment by cjpatoilo** [comment]
@alexiscordova Oops, you're right! This went unnoticed by me. In fact, Milligram use a just once break point to improve readability of the information. Already correct this on homepage and source code. Thanks a lot for the info!
