### ISSUE TITLE
Nav bar as part of milligram?

### ISSUE THREAD

**Issue by alexjj** [milligram/milligram#70]
Love the look of this framework, great job!

Upon trying it out I realised that the nav bar that's part of the [homepage](https://milligram.github.io/) isn't actually part of milligram. Actually, a few things of the homepage aren't part of milligram. It was easy for me to add it to my project, but are there plans to incorporate it as part of milligram?

**Comment by abouthiroppy** [comment]
> The idea is great but my intention is to keep the Milligram as light as possible, supporting the feature minimum necessary to initialize a project. BTW, what you are proposing would be a very specific component. I'm closing your request and appreciate their efforts to improve this project.

https://github.com/milligram/milligram/pull/46

**Comment by cjpatoilo** [comment]
Hi @alexjj @abouthiroppy 

In fact, my intention is to keep Milligram as light as possible, supporting the feature minimum necessary to initialize a project. 

You helped me have a great idea! I will create a repository with components produced with Milligram. This should help many people, a place where they can more easily find something that can help it in everyday life.

http://codepen.io/milligram/

**Comment by EmilMoe** [comment]
Doesn't seem to be well known or used, but I would like a range of navbars too

**Comment by Kcchouette** [comment]
Same here.

**Comment by gwleuverink** [comment]
Heya, I'm looking for a framework that can replace bootstrap for me and milligram is a serious contender. 

I could really do with some more examples since I'm not familiar with the framework yet but the codepen link you posed does not work. Do you have another link?

Thanks!

**Comment by cjpatoilo** [comment]
You are giving me great ideas. 😍

**Comment by jrondorf** [comment]
Any outcome?

**Comment by jrondorf** [comment]
Any outcome on the navbar ideas?

**Comment by minimallinux** [comment]
Milligram is pretty good but I would definitely like to see more Nav options, especially for using with Sage 9 (Wordpress) builds, which usually need a nav walker unless someone can correct me on that?, Thanks

**Comment by popey456963** [comment]
@cjpatoilo's link seems dead.  The new link is https://codepen.io/milligramcss/

(Plus, I would definitely be for adding a navbar to Milligram.  I disagree with others saying that it's a narrow thing for people to want, 90% of websites have a navbar.)

**Comment by gyasikn** [comment]
nav bar would be great

**Comment by mhedrick** [comment]
I would like to add that the fact that the github.io site has a navbar led me to believe that the package itself had a navbar.  it's pretty disingenuous.

**Comment by gwleuverink** [comment]
I disagree. The pages document doesn’t state a navbar is a core component anywhere. The fact the page has a navbar does not mean it is part of the framework. It isn’t disingenuous, you simply made a wrong assumption.

**Comment by mhedrick** [comment]
Yes, I thought the package had a navbar until I started reading and found out it didn't.  It honestly surprised me - my expectation in looking at ui packages is that they generally only use the tools they provide.  I looked through the site css - simply styling the `nav` tag and adding some styling for nav links doesn't seem like it would add too much overhead?

**Comment by chuckreynolds** [comment]
^^ all that said... has anybody  implemented a fairly simple navbar w/ logo and menu items that responsively breaks down to a hamburger-type menu on mobile as an example?

**Comment by yebo29** [comment]
> ^^ all that said... has anybody implemented a fairly simple navbar w/ logo and menu items that responsively breaks down to a hamburger-type menu on mobile as an example?

I'm trying my hand on that now using the example included in milligram, using https://github.com/shuedna/Milligram-baseSite-withMenu as reference. I too am very inexperienced with this so may not succeed. 

But I agree with above; a responsive nav is pretty foundational.

**Comment by chuckreynolds** [comment]
updated previous request... CSS only, no JS, especially no jQuery.

**Comment by popey456963** [comment]
[NavBar with no JavaScript or jQuery for Milligram](https://gist.github.com/popey456963/31c44fa431fdfec3e371e14aaa0d1be9).

[Example site with NavBar](https://femto.pw/).

Under the same license as Milligram (MIT).

**Comment by yebo29** [comment]
Good work @popey456963. The only thing is that it doesn't break down to a hamburger style menu. 
I missed the requirement of no JS/jquery, or vanilla JS. Either way I haven't had much success on my end.. yet.

**Comment by popey456963** [comment]
I think normally you want to hide the navigation bar on scroll down, not scroll up?

**Comment by yebo29** [comment]
The code is for scroll down. Sorry, I misspoke

**Comment by chuckreynolds** [comment]
Following up on css-only responsive nav... this one is simple and works great:
https://codepen.io/chuckreynolds/pen/ROaeXv

**Comment by hbast** [comment]
> Following up on css-only responsive nav... this one is simple and works great:
> [codepen.io/chuckreynolds/pen/ROaeXv](https://codepen.io/chuckreynolds/pen/ROaeXv)

Thanks for the link. But how do I put that together? The content of my container scrolls 'behind' the header. There should be some kind of padding.

**Comment by Seia-Soto** [comment]
Just a comment.

If there are pre-built navbar things, building UI will quite faster.
However, don't you guys think it is something useless? I prefer to providing navbar like Semantic-UI style(using the menu to provide navbar).

I think not `too much` is good. :)

**Comment by cjpatoilo** [comment]
Guys, thank you for helping @. For now, I will close this issue. 
If someone needs help feel free to reopen or open a new!
