### ISSUE TITLE
Textarea should set font-family

### ISSUE THREAD

**Issue by tmpfs** [milligram/milligram#71]
Textarea is being applied a `monospace` user agent style for `font-family`, looking in chrome, using `v1.1.0`.

I believe it should use the same font applied to `body`.

**Comment by barrymcgee** [comment]
@tmpfs I'm not seeing this in the demo? https://milligram.github.io/forms.html

Can you provide a CodePen replicating your bug as per the [guidelines](https://github.com/milligram/milligram/blob/master/contributing.md#open-an-issue) please?

**Comment by tmpfs** [comment]
Your page https://milligram.github.io/forms.html looks fine to me in Chrome and Firefox, likely a problem my end, closing as not an issue.
