### ISSUE TITLE
Align column content

### ISSUE THREAD

**Issue by megaghz** [milligram/milligram#75]
Hi there, I need to align column content to the right and wondering if there is any class to do it. Tried with float-right class for my column div with no luck.

thanks

**Comment by cjpatoilo** [comment]
Hi @megaghz 
For you align the content to the right you use the property `text-align`. But if you need to align the column to the right, use the grid system.

**Comment by datiswous** [comment]
Afaik the grid system doesn't actually have a class for aligning columns to the right. If it does, show me the info.
I just overridden that (with _flex-direction: row-reverse_ ) for use with a navigation menu to the right.
