### ISSUE TITLE
wrap columns problem

### ISSUE THREAD

**Issue by megaghz** [milligram/milligram#76]
Why is that when I wrap my row's columns in a nav tag, they stack each other... it works when I unwrap them.

**Comment by cjpatoilo** [comment]
Hi @megaghz could you show me an example? You can use the [Codepen](http://codepen.io/) for this, do not forget to attach the link.

**Comment by megaghz** [comment]
<section class="container">

        <div class="row">

            <nav id="mainnav">
            <div class="menu column column-25">
                <a class="btn" href="#">ABOUT</a>
            </div>
          
          <div class="menu column column-25">
                <a class="btn" href="#">ABOUT</a>
            </div>
          
          <div class="menu column column-25">
                <a class="btn" href="#">ABOUT</a>
            </div>
          
          <div class="menu column column-25">
                <a class="btn" href="#">ABOUT</a>
            </div>
          </nav>
  </div>
</section>

**Comment by megaghz** [comment]
```
<section class="container">

        <div class="row">

            <nav id="mainnav">
            <div class="menu column column-25">
                <a class="btn" href="#">ABOUT</a>
            </div>
          
          <div class="menu column column-25">
                <a class="btn" href="#">ABOUT</a>
            </div>
          
          <div class="menu column column-25">
                <a class="btn" href="#">ABOUT</a>
            </div>
          
          <div class="menu column column-25">
                <a class="btn" href="#">ABOUT</a>
            </div>
          </nav>
  </div>
</section>
```

**Comment by cjpatoilo** [comment]
The `.row` class has defined Flexbox property. This class is also responsible for the behavior of `.column`. Look at these examples:

```
<section class="container">
	<nav id="mainnav">
		<div class="row">
			<div class="menu column">
				<a class="btn" href="#">ABOUT</a>
			</div>
			<div class="menu column">
				<a class="btn" href="#">ABOUT</a>
			</div>
			<div class="menu column">
				<a class="btn" href="#">ABOUT</a>
			</div>
			<div class="menu column">
				<a class="btn" href="#">ABOUT</a>
			</div>
		</div>
	</nav>
</section>
```
or
```
<section class="container">
	<nav class="row" id="mainnav">
		<div class="menu column">
			<a class="btn" href="#">ABOUT</a>
		</div>
		<div class="menu column">
			<a class="btn" href="#">ABOUT</a>
		</div>
		<div class="menu column">
			<a class="btn" href="#">ABOUT</a>
		</div>
		<div class="menu column">
			<a class="btn" href="#">ABOUT</a>
		</div>
	</nav>
</section>
```

You can find more information about the use of grids.
http://milligram.github.io/grids.html

**Comment by megaghz** [comment]
so I can't wrap a row?

**Comment by cjpatoilo** [comment]
Yes, you need

**Comment by jackmcpickle** [comment]
@megaghz this should be fixed in the latest merge https://github.com/milligram/milligram/pull/100 - also see [my example](http://codepen.io/jackmcpickle/pen/XKakpK)

Maybe read up on `display: flex` and how it works - as it only affects its direct children. 
The css-tricks article on flexbox is a great place to start https://css-tricks.com/snippets/css/a-guide-to-flexbox/
