### ISSUE TITLE
Suggestion for a Fancy Button Style

### ISSUE THREAD

**Issue by Mortiferr** [milligram/milligram#78]
I think the whole project could benefit from `transition: all 0.3s ease 0s;` on the animations to make it look smoother.

I designed a simple button and a link that looks like a button with these transitions. I called the classes `fancy-button` and `fancy-link` in the demo. Hope you like the idea.

[buttons for milligram.zip](https://github.com/milligram/milligram/files/137406/buttons.for.milligram.zip)

**Comment by kevbook** [comment]
transitions and such things, need to be in the user land, not in the framework.

**Comment by elad** [comment]
What @kevbook said. The beauty of this framework is that it **doesn't** have all the bells and whistles of other, more bloated frameworks.
