### ISSUE TITLE
Meteor Package - noahvlncrt:milligram

### ISSUE THREAD

**Issue by NoahVlncrt** [milligram/milligram#8]
I have just organized and released your code as meteor package. Don't worry I have credited you properly and I'm looking forward to keeping up with this package for your future releases. If you would like to take control and tackle this project I understand. contact me.

I didn't just make a pull request and add the package.js file because I do not want the version people install on there projects cluttered with files like that. It won't be shown but it'll be there. I hope you like this and maybe just maybe you could add something in the readme. That tells you how you would install it in a meteor project just so people know it's a thing that they can do.

**install with Meteor**
```sh
meteor add noahvlncrt:milligram
```

https://atmospherejs.com/noahvlncrt/milligram

**Comment by cjpatoilo** [comment]
Great job @NoahVlncrt.
I wait for your PR. Thanks a lot!

**Comment by NoahVlncrt** [comment]
Just sent in my pull request. The meteor package info is under the branch meteor-package
