### ISSUE TITLE
column-100

### ISSUE THREAD

**Issue by jonathan-s** [milligram/milligram#81]
Shouldn't there be a `column-100` as well. In case you want to specify that you indeed want an element to take the entire width. If you just specify `column` and you put in another it won't take the entire width.

**Comment by cjpatoilo** [comment]
Hey @jonathan-s I dont know. I see this case as a new line. What do you think?

**Comment by elad** [comment]
Two `column-100` are effectively two rows, so why not just use `row` with one `column` inside it? it feels much cleaner to me.
