### ISSUE TITLE
Grid mobile responsive for different widths

### ISSUE THREAD

**Issue by enkota** [milligram/milligram#83]
Hey, having a great time using milligram...really lightweight.

Coming from bootstrap's grids i'm used to having say `<div class="col md-7">` going full width on mobile devices. Is this possible with milligram? At the moment I am using `<div class="column column-70">` but when it goes down to small screen sizes the with is still 70% not 100%. 

Cheers!

Scott

**Comment by cjpatoilo** [comment]
Hey @scopeak 

So, the grid system does not have the same behavior and support as other framework: Bootstrap, Foundation .. BTW, this is a great idea for the next version.

**Comment by scopeak** [comment]
No worries! I ended up replacing with the bootstrap grids and keeping the rest for now. Would be a great addition though I think :+1:

**Comment by netoguimaraes** [comment]
Hello @cjpatoilo and @scopeak 

I looked at the milligram project and the only thing I've missed was a grid system minimalist and lightweight. I have an small project that proposes it: a minimalist grid system. Maybe, it need a improvement on syntax for get more readable for humans. Could you guys take a look? I think it's a good alternative to get this issue closed.
https://github.com/netoguimaraes/sandal-grid

as I said, we can improve the grid for embed at milligram, if you like the idea. Just open issues in the sandal-grid and we see what goes on;

**Comment by ruvido** [comment]
+1 for this, much needed. It's not difficult to do, just don't know how much _weight_ we'are gonna put :D

**Comment by unip** [comment]
Same problem here.
I agree with @cjpatoilo, make it as a new feature for the next version please. I started to switch from bootstrap to milligram because of its lightweight and simplicity dividing the grid since it uses flexbox :heart: .

**Comment by cjpatoilo** [comment]
@unip @ruvido @netoguimaraes @enkota I appreciate it, these words mean a lot to me, thank you.

For now I will close this issue. Let me know if there is anything else we can help and I will reopen this issue as soon as possible.
