### ISSUE TITLE
Grids are broken in IE11

### ISSUE THREAD

**Issue by davedele** [milligram/milligram#84]
In the demo, the grid items  collapse on one another. Only seeing this in IE11.  
Also, there is no full list of supported browsers in the docs.

**Comment by cjpatoilo** [comment]
Hi @davedele You can tell which version of your OS? You can also provide some print screen?

**Comment by davedele** [comment]
Hey @cjpatoilo, thanks for your reply. To be more specific, at any mobile breakpoint you get what you see in the attached image. 

I'm using IE11 on Windows7
![untitled-3](https://cloud.githubusercontent.com/assets/3038776/14028228/75e5f570-f1c9-11e5-9fbf-f848a477b88e.jpg)

**Comment by cjpatoilo** [comment]
Hey @davedele For IE there is a partial support due to the great amount of bugs ([see known issues](http://caniuse.com/#search=flexbox ))

Thank you for reporting this issue. I will improve this information on the homepage.

**Comment by davedele** [comment]
Thanks @cjpatoilo, Here's a quick workaround for IE11: 

I use a bit of js to find the UserAgent [http://rog.ie/blog/html5-boilerplate-addon](url) 

Then I add a new media query:
```
@media screen and (max-width: 40em) {
   
    html[data-useragent*='rv:11.0'] .row .column {
        flex: none;
    }
}
```

What's breaking it in IE is the "flex:1" in the class ".row .column".

**Comment by dubcanada** [comment]
Change `.row .column` from `flex: 1;` to `flex: 1 1 auto;`

Works better, and it works for all browsers. Including IE11.
