### ISSUE TITLE
Focus states for links

### ISSUE THREAD

**Issue by alexcarpenter** [milligram/milligram#85]
Within links we should add the focus state for accessibility reasons. 

```sass
a
  color: $color-primary
  text-decoration: none

  &:hover,
  &:focus
    color: $color-secondary
```

https://24ways.org/2009/dont-lose-your-focus

**Comment by sudheerDev** [comment]
@alexcarpenter Most of the other tags do have focus states.I added focus for a tag. Thanks for pointing it out
