### ISSUE TITLE
Root font-size update

### ISSUE THREAD

**Issue by equinusocio** [milligram/milligram#87]
Please update the root font-size to 100% so 1rem will be 16px (instead of 1.5rem=16px) for a more easy calc

**Comment by alexcarpenter** [comment]
@equinusocio 1.6rem = 16px when the root font size is set to 62.5%.

**Comment by equinusocio** [comment]
@alexcarpenter not really no. No more.

- http://kyleschaeffer.com/development/css-font-size-em-vs-px-vs-pt-vs/

- http://stackoverflow.com/questions/24542508/default-html-font-size

- http://alistapart.com/article/howtosizetextincss

- http://www.w3schools.com/css/css_font.asp
Note: If you do not specify a font size, the default size for normal text, like paragraphs, is 16px (16px=1em).

And many other references..

**Comment by cjpatoilo** [comment]
Hi @equinusocio  

So, I understand your proposal and I think it very interesting, but I believe it is easier to maintain a conversion based on decimals. I just do not understand when you say that `1.6rem = 16px` is not correct.

![image](https://cloud.githubusercontent.com/assets/1542831/17463910/95b58f42-5ca8-11e6-9667-ba6128e8d426.png)

**Comment by equinusocio** [comment]
@cjpatoilo This is not a proposal :) is a fact. 

In you screenshot you have `font-size: 62.5%` in your html. To get `16px` you have to write `1.6em` it's ok, but the only advantage is the conversion based on decimals.

Instead if you use `font-size: 100%` in your html to get 16px you have to simply write `1rem`, and it's relative simple to get the px conversion, just do `( *px / 16 )`. So if you want to set a `48px` font-size, just do (`48/16 = 3rem`).

There is a lot of advantages from this method, the first one is that you can use the `rem` unit that is relative to the root font-size (`:root {}` or `html {}`) and with a simple media query you can change the whole site typography and make her scalable. 

We assume to be on a preprocessor:

```sass
:root {
  font-size: 100%;
  
  @media screen and (mid-width: 40em) {
    font-size: 80%;
  }

  @media screen and (mid-width: 80em) {
    font-size: 60%;
  }
}
```

More info here:
http://zellwk.com/blog/responsive-typography/

This is a method introduced a few years ago and now it should be implemented as a basic alternative to those who do not want to use the viewport units

**Comment by cjpatoilo** [comment]
Hey @equinusocio Now I will not change that. It is currently working very well this way, but maybe in the future I will try to better understand the need for this use. Who knows.. For now I will close this issue. Feel free to reopen this issue if this doesn't do the trick for you. 

Thank you very much for your contribution

**Comment by berarma** [comment]
I don't understand all the fuss about the decimal numbers math. I would want 1rem to mean the default browser font size, which is normally the minimal good font size for readability, and not caring about the resulting size in pixels. If I want double the size of the default browser size I have to type 3.2rem when using milligram and 2rem everywhere else.

It's not even defined as 10px, it's 62.5% the default browser font size, whatever that is. This results in a very tiny font size unusable on any browser, forcing us to use something like 1.6rem or whatever gives us back the sane default.

Are we trying to cover the fact that we're still designing with pixels in mind in 2023? No need, use pixel units without shame and let rem/em be used for all other cases.

Just my 2c.
