### ISSUE TITLE
Include src in the bower package

### ISSUE THREAD

**Issue by roryprimrose** [milligram/milligram#89]
Currently the bower package does not include the src folder. This means that we can't use sass + gulp to customise the milligram output. For example, I might want to ditch grid and code to get a smaller output and I might want to make changes to the colour variables. This is currently not possible because the only two avenues I have to play with are css via bower or css via CDN.

**Comment by clayreimann** [comment]
@cjpatoilo This should depreciate all of the `milligram/milligram-*` packages since those packages aren't being maintained.

**Comment by cjpatoilo** [comment]
@roryprimrose @clayreimann This month I will arrange the house to leave everything in order. 
Thank you for your attention, I like that.

**Comment by TimonVS** [comment]
Please also include the src folder in the npm package :).

**Comment by cjpatoilo** [comment]
@roryprimrose @clayreimann @TimonVS  I had chosen create independent modules for each preprocessor (less, sass, stylus..) to optimize the use, keeping the main repository with pure CSS. I'm thinking of a solution to keep everyone in a single repository, but I do not know how far it can really help or further complicate the use of Milligram. What do you think?

**Comment by clayreimann** [comment]
@cjpatoilo I think the best course is to write it once in sass/less/scss/whatever and then provide transpiled versions in different directories in `dist/`. 

Most people will be pulling this down on their build server and will then recompile/flatten it into their stylesheet bundle so will never notice the extra ~100kb to download all the variants. For people who only want the compiled CSS they can pull it down client-side using `githubcdn` or `npmcdn`.

The advantage to doing it this way is that everything will always stay in sync between the various markup languages.

**Comment by TimonVS** [comment]
I completely agree with @clayreimann. Keeping everything in one repo will also make it easier for contributors to contribute something (instead of having to contribute to several different repos).

**Comment by cjpatoilo** [comment]
@roryprimrose @clayreimann @TimonVS Sorry guys!!! I've been out for a long time. I am updating all repositories during these days and everything will return to normal.

BTW you have reason on the maintainability, it will certainly be much smaller. But I'll keep the same flow with specific repositories for each preprocessor. For now I will close this request, but if there is any doubt I will reopen this issue again.
