### ISSUE TITLE
 µg - Simple Milligram Customizer

### ISSUE THREAD

**Issue by vkeusebio** [milligram/milligram#9]
hello, I made [µg (microgram)](https://ug-web.herokuapp.com/), a simple customizer for milligram as suggested on #5.

Simply choose the modules that you want to include on your custom build and hit `Download`. It also comes with normalize to save you time. I know its pretty basic and lacks other options such as live preview, color picker, font family editor, etc. but it does the job.

**Comment by alisonmonteiro** [comment]
Wow! Really good, @vkeusebio!

**Comment by cjpatoilo** [comment]
This is awesome!
Great work, guy. =D

If you want, I can try to help you with that.

**Comment by vkeusebio** [comment]
@alisonmonteiro @cjpatoilo thanks! I'm glad you liked it
