### ISSUE TITLE
SCSS port

### ISSUE THREAD

**Issue by TimonVS** [milligram/milligram#93]
I created a Scss port because I wanted to import the files in my project.

I'm not sure if we should merge the project into one or not. I can provide a script that automatically converts all the Sass files to Scss when building the project.

Link to fork: https://github.com/TimonVS/milligram-scss

**Comment by bencoveney** [comment]
Just FYI, there is already a project for this - [https://github.com/milligram/milligram-scss](https://github.com/milligram/milligram-scss)

I've got no idea how up to date it is though and I guess it could be better documented that it exists.

**Comment by TimonVS** [comment]
Wow, I don't know how I missed that!
Thanks. I'll check if it's up to date.
